/**
 * Connector definitions.
 *
 * Every `package` here was checked against the public npm registry, and every
 * `icon` title against the Simple Icons index, before being added. Candidates
 * that failed either check were dropped rather than guessed at.
 *
 * `icon` is the Simple Icons *title*, which is their lookup key — it is consumed
 * by build-icons.mjs, not written into the manifest.
 */

/** Shorthand for a required string parameter. */
const req = (description) => ({ type: "string", description, required: true });
/** Shorthand for an optional string parameter. */
const opt = (description) => ({ type: "string", description });
const optNum = (description) => ({ type: "number", description });

export const CONNECTORS = [
  {
    slug: "airtable",
    title: "Airtable",
    icon: "Airtable",
    package: "airtable-mcp-server",
    category: "Data & Analytics",
    summary:
      "Read and update Airtable bases, tables and records. Use for lightweight operational data an agent must query or maintain.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://airtable.com",
    authNote: "Requires a personal access token with scopes for the bases you want to reach.",
    tools: [
      {
        name: "list_bases",
        description: "Lists the bases the token can reach.",
        readOnly: true,
      },
      {
        name: "list_records",
        description: "Lists records from a table, optionally filtered by a formula.",
        readOnly: true,
        params: {
          base_id: req("Base identifier."),
          table: req("Table name or id."),
          filter_by_formula: opt("Airtable formula limiting which records return."),
          max_records: optNum("Maximum records to return."),
        },
      },
      {
        name: "get_record",
        description: "Returns one record with all its fields.",
        readOnly: true,
        params: { base_id: req("Base identifier."), table: req("Table name or id."), record_id: req("Record identifier.") },
      },
      {
        name: "create_record",
        description: "Creates a record in a table.",
        params: { base_id: req("Base identifier."), table: req("Table name or id."), fields: req("JSON object of field values.") },
      },
      {
        name: "update_record",
        description: "Updates fields on an existing record.",
        params: {
          base_id: req("Base identifier."),
          table: req("Table name or id."),
          record_id: req("Record identifier."),
          fields: req("JSON object of field values to change."),
        },
      },
    ],
  },
  {
    slug: "asana",
    title: "Asana",
    icon: "Asana",
    package: "@roychri/mcp-server-asana",
    category: "Documents & Communication",
    summary:
      "Read and update Asana projects, tasks and comments. Use to check assignments, track delivery and file work.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://asana.com",
    authNote: "Requires an Asana personal access token.",
    tools: [
      { name: "list_workspaces", description: "Lists workspaces the token can reach.", readOnly: true },
      {
        name: "search_tasks",
        description: "Searches tasks by text within a workspace.",
        readOnly: true,
        params: { workspace: req("Workspace identifier."), query: req("Text to search for.") },
      },
      {
        name: "get_task",
        description: "Returns a task with assignee, due date and status.",
        readOnly: true,
        params: { task_id: req("Task identifier.") },
      },
      {
        name: "create_task",
        description: "Creates a task in a project.",
        params: {
          project_id: req("Project identifier."),
          name: req("Task title."),
          notes: opt("Task description."),
          assignee: opt("User identifier or email."),
          due_on: opt("Due date, YYYY-MM-DD."),
        },
      },
      {
        name: "add_comment",
        description: "Adds a comment to a task.",
        params: { task_id: req("Task identifier."), text: req("Comment body.") },
      },
    ],
  },
  {
    slug: "auth0",
    title: "Auth0",
    icon: "Auth0",
    package: "@auth0/auth0-mcp-server",
    category: "Security",
    summary:
      "Inspect Auth0 tenants, applications, connections and logs. Use to diagnose authentication failures and audit access configuration.",
    auth: "oauth2",
    scopes: ["read"],
    homepage: "https://auth0.com",
    authNote: "Authenticates against your Auth0 tenant; grant only read scopes unless changes are intended.",
    tools: [
      { name: "list_applications", description: "Lists applications in the tenant.", readOnly: true },
      { name: "list_connections", description: "Lists identity connections and their strategies.", readOnly: true },
      {
        name: "get_logs",
        description: "Returns recent authentication log events.",
        readOnly: true,
        params: { query: opt("Log search query."), limit: optNum("Maximum events to return.") },
      },
      {
        name: "list_users",
        description: "Searches users in the tenant directory.",
        readOnly: true,
        params: { query: opt("Lucene query over user fields."), limit: optNum("Maximum users to return.") },
      },
    ],
  },
  {
    slug: "bitbucket",
    title: "Bitbucket",
    icon: "Bitbucket",
    package: "@nexus2520/bitbucket-mcp-server",
    category: "Software Engineering",
    summary:
      "Browse Bitbucket repositories, pull requests and pipelines. Use for code review and release checks on Bitbucket-hosted code.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://bitbucket.org",
    authNote: "Requires a Bitbucket app password with repository and pull request scopes.",
    tools: [
      {
        name: "list_pull_requests",
        description: "Lists open pull requests for a repository.",
        readOnly: true,
        params: { workspace: req("Workspace slug."), repo: req("Repository slug."), state: opt("OPEN, MERGED or DECLINED.") },
      },
      {
        name: "get_pull_request",
        description: "Returns a pull request with its description and reviewers.",
        readOnly: true,
        params: { workspace: req("Workspace slug."), repo: req("Repository slug."), id: req("Pull request number.") },
      },
      {
        name: "get_diff",
        description: "Returns the diff for a pull request.",
        readOnly: true,
        params: { workspace: req("Workspace slug."), repo: req("Repository slug."), id: req("Pull request number.") },
      },
      {
        name: "add_pr_comment",
        description: "Comments on a pull request.",
        params: {
          workspace: req("Workspace slug."),
          repo: req("Repository slug."),
          id: req("Pull request number."),
          text: req("Comment body."),
        },
      },
    ],
  },
  {
    slug: "datadog",
    title: "Datadog",
    icon: "Datadog",
    package: "@winor30/mcp-server-datadog",
    category: "Cloud & DevOps",
    summary:
      "Query Datadog metrics, monitors, logs and incidents. Use to investigate alerts and check service health.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://datadoghq.com",
    authNote: "Requires a Datadog API key and application key.",
    tools: [
      {
        name: "query_metrics",
        description: "Queries a metric over a time range.",
        readOnly: true,
        params: { query: req("Datadog metric query."), from: req("Start time, epoch seconds."), to: req("End time, epoch seconds.") },
      },
      {
        name: "list_monitors",
        description: "Lists monitors and their current states.",
        readOnly: true,
        params: { group_states: opt("Filter by state, such as alert.") },
      },
      {
        name: "search_logs",
        description: "Searches logs over a time range.",
        readOnly: true,
        params: { query: req("Log search query."), from: opt("Start time."), to: opt("End time."), limit: optNum("Maximum entries.") },
      },
      { name: "list_incidents", description: "Lists recent incidents.", readOnly: true },
    ],
  },
  {
    slug: "discord",
    title: "Discord",
    icon: "Discord",
    package: "mcp-discord",
    category: "Documents & Communication",
    summary:
      "Read and post to Discord channels. Use for community support, release announcements and monitoring discussion.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://discord.com",
    authNote: "Requires a bot token, and the bot must be invited to the servers you want to reach.",
    tools: [
      { name: "list_channels", description: "Lists channels in a server.", readOnly: true, params: { guild_id: req("Server identifier.") } },
      {
        name: "read_messages",
        description: "Reads recent messages from a channel.",
        readOnly: true,
        params: { channel_id: req("Channel identifier."), limit: optNum("Maximum messages to return.") },
      },
      {
        name: "send_message",
        description: "Posts a message to a channel.",
        params: { channel_id: req("Channel identifier."), content: req("Message text.") },
      },
    ],
  },
  {
    slug: "elasticsearch",
    title: "Elasticsearch",
    icon: "Elasticsearch",
    package: "@elastic/mcp-server-elasticsearch",
    category: "Data & Analytics",
    summary:
      "Search and inspect Elasticsearch indices. Use for log analysis, full-text search and index diagnostics.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://elastic.co",
    authNote: "Requires a cluster URL and an API key with read privileges on the indices you expose.",
    tools: [
      { name: "list_indices", description: "Lists indices with document counts and size.", readOnly: true },
      {
        name: "get_mappings",
        description: "Returns the field mappings for an index.",
        readOnly: true,
        params: { index: req("Index name.") },
      },
      {
        name: "search",
        description: "Runs a query DSL search against an index.",
        readOnly: true,
        params: { index: req("Index name."), query: req("Query DSL as JSON."), size: optNum("Maximum hits to return.") },
      },
    ],
  },
  {
    slug: "trello",
    title: "Trello",
    icon: "Trello",
    package: "@delorenj/mcp-server-trello",
    category: "Documents & Communication",
    summary:
      "Read and update Trello boards, lists and cards. Use for lightweight project tracking and status checks.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://trello.com",
    authNote: "Requires a Trello API key and token.",
    tools: [
      { name: "list_boards", description: "Lists boards the token can reach.", readOnly: true },
      { name: "get_lists", description: "Lists the lists on a board.", readOnly: true, params: { board_id: req("Board identifier.") } },
      {
        name: "get_cards",
        description: "Returns cards in a list with their labels and due dates.",
        readOnly: true,
        params: { list_id: req("List identifier.") },
      },
      {
        name: "create_card",
        description: "Creates a card in a list.",
        params: { list_id: req("List identifier."), name: req("Card title."), description: opt("Card body."), due: opt("Due date, ISO 8601.") },
      },
      {
        name: "move_card",
        description: "Moves a card to another list.",
        params: { card_id: req("Card identifier."), list_id: req("Destination list identifier.") },
      },
    ],
  },
  {
    slug: "salesforce",
    title: "Salesforce",
    icon: "Salesforce",
    package: "@salesforce/mcp",
    category: "Sales & Marketing",
    summary:
      "Query and update Salesforce records with SOQL. Use for pipeline questions, account lookups and CRM hygiene.",
    auth: "oauth2",
    scopes: ["read", "write"],
    homepage: "https://salesforce.com",
    authNote: "Authenticates against your Salesforce org; the connected user's permissions apply.",
    tools: [
      {
        name: "run_soql",
        description: "Runs a SOQL query and returns matching records.",
        readOnly: true,
        params: { query: req("SOQL query text.") },
      },
      {
        name: "describe_object",
        description: "Returns the fields and types of an object.",
        readOnly: true,
        params: { object: req("API name, such as Opportunity.") },
      },
      {
        name: "get_record",
        description: "Returns one record by id.",
        readOnly: true,
        params: { object: req("API name."), record_id: req("Record identifier.") },
      },
      {
        name: "update_record",
        description: "Updates fields on a record.",
        params: { object: req("API name."), record_id: req("Record identifier."), fields: req("JSON object of field values.") },
      },
    ],
  },

  /* ------------------------------------------------------- commerce & money */
  {
    slug: "shopify",
    title: "Shopify",
    icon: "Shopify",
    package: "@shopify/dev-mcp",
    category: "Sales & Marketing",
    summary:
      "Query Shopify store data and developer documentation. Use for order lookups, catalogue questions and storefront development.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://shopify.com",
    authNote: "Requires a Shopify Admin API access token for store data.",
    tools: [
      { name: "search_docs", description: "Searches Shopify developer documentation.", readOnly: true, params: { query: req("Search text.") } },
      { name: "introspect_admin_schema", description: "Returns the Admin GraphQL schema for a type.", readOnly: true, params: { type: opt("Type name to inspect.") } },
      { name: "list_orders", description: "Lists recent orders with status and total.", readOnly: true, params: { status: opt("Filter by fulfilment status."), limit: optNum("Maximum orders.") } },
      { name: "get_product", description: "Returns a product with variants and inventory.", readOnly: true, params: { product_id: req("Product identifier.") } },
    ],
  },
  {
    slug: "paypal",
    title: "PayPal",
    icon: "PayPal",
    package: "@paypal/mcp",
    category: "Sales & Marketing",
    summary:
      "Inspect PayPal transactions, invoices and disputes. Use for payment reconciliation and billing support.",
    auth: "oauth2",
    scopes: ["read"],
    homepage: "https://paypal.com",
    authNote: "Requires PayPal API credentials for your business account.",
    tools: [
      { name: "list_transactions", description: "Lists transactions in a date range.", readOnly: true, params: { start_date: req("Start date, ISO 8601."), end_date: req("End date, ISO 8601.") } },
      { name: "get_invoice", description: "Returns an invoice with its line items and status.", readOnly: true, params: { invoice_id: req("Invoice identifier.") } },
      { name: "list_disputes", description: "Lists open disputes needing a response.", readOnly: true },
    ],
  },

  /* ---------------------------------------------------- support & messaging */
  {
    slug: "zendesk",
    title: "Zendesk",
    icon: "Zendesk",
    package: "zendesk-mcp-server",
    category: "Documents & Communication",
    summary:
      "Read and update Zendesk tickets and users. Use for support triage and finding recurring customer problems.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://zendesk.com",
    authNote: "Requires a Zendesk subdomain, email and API token.",
    tools: [
      { name: "search_tickets", description: "Searches tickets by query.", readOnly: true, params: { query: req("Zendesk search query."), limit: optNum("Maximum tickets.") } },
      { name: "get_ticket", description: "Returns a ticket with its comment thread.", readOnly: true, params: { ticket_id: req("Ticket identifier.") } },
      { name: "add_comment", description: "Adds a public or internal comment to a ticket.", params: { ticket_id: req("Ticket identifier."), body: req("Comment text."), public: opt("true for a public reply.") } },
      { name: "update_ticket", description: "Changes a ticket's status, priority or assignee.", params: { ticket_id: req("Ticket identifier."), status: opt("New status."), priority: opt("New priority."), assignee_id: opt("Assignee identifier.") } },
    ],
  },
  {
    slug: "twilio",
    title: "Twilio",
    icon: "Twilio",
    package: "@twilio-alpha/mcp",
    category: "Documents & Communication",
    summary:
      "Send messages and inspect Twilio logs. Use for notification delivery and diagnosing failed sends.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://twilio.com",
    authNote: "Requires a Twilio account SID and auth token. Sending messages costs money.",
    tools: [
      { name: "list_messages", description: "Lists recent messages with delivery status.", readOnly: true, params: { to: opt("Filter by recipient."), limit: optNum("Maximum messages.") } },
      { name: "send_message", description: "Sends an SMS or WhatsApp message. Costs money.", params: { to: req("Recipient number in E.164 format."), from: req("Sender number."), body: req("Message text.") } },
      { name: "get_call_logs", description: "Lists recent calls with duration and status.", readOnly: true, params: { limit: optNum("Maximum calls.") } },
    ],
  },
  {
    slug: "sendgrid",
    title: "SendGrid",
    icon: "SendGrid",
    package: "sendgrid-mcp",
    category: "Sales & Marketing",
    summary:
      "Send transactional email and inspect delivery statistics. Use for email operations and deliverability checks.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://sendgrid.com",
    authNote: "Requires a SendGrid API key. Restrict it to the scopes you need.",
    tools: [
      { name: "get_stats", description: "Returns delivery, open and bounce statistics.", readOnly: true, params: { start_date: req("Start date, YYYY-MM-DD."), end_date: opt("End date, YYYY-MM-DD.") } },
      { name: "list_suppressions", description: "Lists bounced and unsubscribed addresses.", readOnly: true },
      { name: "send_email", description: "Sends an email. Delivers to real recipients.", params: { to: req("Recipient address."), from: req("Verified sender address."), subject: req("Subject line."), body: req("Message body.") } },
    ],
  },

  /* ---------------------------------------------------------- data stores */
  {
    slug: "mongodb",
    title: "MongoDB",
    icon: "MongoDB",
    package: "mongodb-mcp-server",
    category: "Data & Analytics",
    summary:
      "Query and inspect MongoDB collections. Use for document lookups, aggregation and schema exploration.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://mongodb.com",
    authNote: "Requires a connection string. Use a read-only user unless writes are intended.",
    tools: [
      { name: "list_collections", description: "Lists collections in a database.", readOnly: true, params: { database: req("Database name.") } },
      { name: "find", description: "Runs a find query against a collection.", readOnly: true, params: { collection: req("Collection name."), filter: opt("Query filter as JSON."), limit: optNum("Maximum documents.") } },
      { name: "aggregate", description: "Runs an aggregation pipeline.", readOnly: true, params: { collection: req("Collection name."), pipeline: req("Pipeline stages as JSON array.") } },
      { name: "get_indexes", description: "Lists indexes on a collection.", readOnly: true, params: { collection: req("Collection name.") } },
    ],
  },
  {
    slug: "redis",
    title: "Redis",
    icon: "Redis",
    package: "@modelcontextprotocol/server-redis",
    category: "Data & Analytics",
    summary:
      "Read and write Redis keys. Use for cache inspection, debugging session state and checking queue depth.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://redis.io",
    authNote: "Requires a Redis connection URL.",
    tools: [
      { name: "get", description: "Returns the value at a key.", readOnly: true, params: { key: req("Key name.") } },
      { name: "list_keys", description: "Lists keys matching a pattern.", readOnly: true, params: { pattern: opt("Glob pattern, such as session:*.") } },
      { name: "set", description: "Sets a key to a value, optionally with expiry.", params: { key: req("Key name."), value: req("Value to store."), ttl_seconds: optNum("Expiry in seconds.") } },
      { name: "delete", description: "Deletes a key.", params: { key: req("Key name.") } },
    ],
  },
  {
    slug: "mysql",
    title: "MySQL",
    icon: "MySQL",
    package: "@benborla29/mcp-server-mysql",
    category: "Data & Analytics",
    summary:
      "Query MySQL databases and inspect schemas. Use for reporting, debugging and understanding an unfamiliar database.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://mysql.com",
    authNote: "Requires connection details. Use a read-only user; the server can be configured to reject writes.",
    tools: [
      { name: "list_tables", description: "Lists tables with row estimates.", readOnly: true },
      { name: "describe_table", description: "Returns columns, types and indexes for a table.", readOnly: true, params: { table: req("Table name.") } },
      { name: "query", description: "Runs a read-only SQL query.", readOnly: true, params: { sql: req("SELECT statement."), limit: optNum("Maximum rows to return.") } },
    ],
  },
  {
    slug: "clickhouse",
    title: "ClickHouse",
    icon: "ClickHouse",
    package: "mcp-clickhouse",
    category: "Data & Analytics",
    summary:
      "Query ClickHouse for analytical workloads. Use for large-scale aggregation over event and log data.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://clickhouse.com",
    authNote: "Requires host, port and credentials for a read-only user.",
    tools: [
      { name: "list_databases", description: "Lists databases on the cluster.", readOnly: true },
      { name: "list_tables", description: "Lists tables with engine and size.", readOnly: true, params: { database: req("Database name.") } },
      { name: "query", description: "Runs a SELECT query.", readOnly: true, params: { sql: req("SELECT statement."), limit: optNum("Maximum rows.") } },
    ],
  },
  {
    slug: "snowflake",
    title: "Snowflake",
    icon: "Snowflake",
    package: "mcp-snowflake-server",
    category: "Data & Analytics",
    summary:
      "Query Snowflake warehouses and inspect schemas. Use for analytics and warehouse cost investigation.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://snowflake.com",
    authNote: "Requires account, warehouse, role and credentials. Queries consume warehouse credits.",
    tools: [
      { name: "list_databases", description: "Lists databases and schemas.", readOnly: true },
      { name: "describe_table", description: "Returns a table's columns and types.", readOnly: true, params: { table: req("Fully qualified table name.") } },
      { name: "query", description: "Runs a SELECT query. Consumes credits.", readOnly: true, params: { sql: req("SELECT statement."), limit: optNum("Maximum rows.") } },
    ],
  },
  {
    slug: "databricks",
    title: "Databricks",
    icon: "Databricks",
    package: "databricks-mcp-server",
    category: "Data & Analytics",
    summary:
      "Query Databricks tables and inspect jobs. Use for lakehouse analytics and pipeline monitoring.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://databricks.com",
    authNote: "Requires a workspace URL and personal access token.",
    tools: [
      { name: "list_catalogs", description: "Lists Unity Catalog catalogs and schemas.", readOnly: true },
      { name: "query", description: "Runs a SQL query against a warehouse.", readOnly: true, params: { sql: req("SELECT statement."), warehouse_id: opt("SQL warehouse identifier.") } },
      { name: "list_jobs", description: "Lists jobs with their last run status.", readOnly: true },
    ],
  },
  {
    slug: "upstash",
    title: "Upstash",
    icon: "Upstash",
    package: "@upstash/mcp-server",
    category: "Data & Analytics",
    summary:
      "Manage Upstash Redis and Kafka resources. Use for serverless data infrastructure operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://upstash.com",
    authNote: "Requires an Upstash management API key.",
    tools: [
      { name: "list_databases", description: "Lists Redis databases with region and size.", readOnly: true },
      { name: "get_usage", description: "Returns command counts and storage for a database.", readOnly: true, params: { database_id: req("Database identifier.") } },
      { name: "create_database", description: "Creates a Redis database. Incurs cost.", params: { name: req("Database name."), region: req("Region identifier.") } },
    ],
  },
  {
    slug: "amazon-s3",
    title: "Amazon S3",
    icon: "Amazon S3",
    package: "s3-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "List and read objects in S3 buckets. Use for inspecting data lakes, logs and stored artefacts.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://aws.amazon.com/s3",
    authNote: "Requires AWS credentials. Grant read-only bucket policies unless writes are intended.",
    tools: [
      { name: "list_buckets", description: "Lists buckets the credentials can reach.", readOnly: true },
      { name: "list_objects", description: "Lists objects under a prefix.", readOnly: true, params: { bucket: req("Bucket name."), prefix: opt("Key prefix to filter by."), limit: optNum("Maximum objects.") } },
      { name: "get_object", description: "Reads an object's contents.", readOnly: true, params: { bucket: req("Bucket name."), key: req("Object key.") } },
    ],
  },

  /* ------------------------------------------------------ cloud & devops */
  {
    slug: "terraform",
    title: "Terraform",
    icon: "Terraform",
    package: "terraform-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Look up Terraform providers, modules and registry documentation. Use when writing or reviewing infrastructure code.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://terraform.io",
    authNote: "No credentials needed for registry lookups.",
    tools: [
      { name: "search_modules", description: "Searches the Terraform registry for modules.", readOnly: true, params: { query: req("Search text.") } },
      { name: "get_provider_docs", description: "Returns documentation for a provider resource.", readOnly: true, params: { provider: req("Provider name, such as aws."), resource: req("Resource type name.") } },
      { name: "get_module", description: "Returns a module's inputs, outputs and versions.", readOnly: true, params: { module: req("Module path, such as terraform-aws-modules/vpc/aws.") } },
    ],
  },
  {
    slug: "circleci",
    title: "CircleCI",
    icon: "CircleCI",
    package: "@circleci/mcp-server-circleci",
    category: "Cloud & DevOps",
    summary:
      "Inspect CircleCI pipelines, workflows and build failures. Use to diagnose why a build broke.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://circleci.com",
    authNote: "Requires a CircleCI personal API token.",
    tools: [
      { name: "list_pipelines", description: "Lists recent pipelines for a project.", readOnly: true, params: { project_slug: req("Project slug, such as gh/org/repo.") } },
      { name: "get_build_failure", description: "Returns the failing step and its log output.", readOnly: true, params: { project_slug: req("Project slug."), job_number: req("Job number.") } },
      { name: "list_workflows", description: "Lists workflows in a pipeline with their status.", readOnly: true, params: { pipeline_id: req("Pipeline identifier.") } },
    ],
  },
  {
    slug: "jenkins",
    title: "Jenkins",
    icon: "Jenkins",
    package: "jenkins-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Inspect Jenkins jobs, builds and console output. Use for CI diagnostics on self-hosted pipelines.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://jenkins.io",
    authNote: "Requires a Jenkins URL, username and API token.",
    tools: [
      { name: "list_jobs", description: "Lists jobs with their last build status.", readOnly: true },
      { name: "get_build", description: "Returns a build's result, duration and cause.", readOnly: true, params: { job: req("Job name."), build_number: opt("Build number, or last if omitted.") } },
      { name: "get_console_output", description: "Returns the console log for a build.", readOnly: true, params: { job: req("Job name."), build_number: req("Build number.") } },
    ],
  },
  {
    slug: "argo-cd",
    title: "Argo CD",
    icon: "Argo",
    package: "argocd-mcp",
    category: "Cloud & DevOps",
    summary:
      "Inspect Argo CD applications and sync status. Use to check what is deployed and why a sync failed.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://argo-cd.readthedocs.io",
    authNote: "Requires an Argo CD server URL and auth token.",
    tools: [
      { name: "list_applications", description: "Lists applications with sync and health status.", readOnly: true },
      { name: "get_application", description: "Returns an application's resources and last sync result.", readOnly: true, params: { name: req("Application name.") } },
      { name: "get_sync_history", description: "Returns recent sync operations for an application.", readOnly: true, params: { name: req("Application name.") } },
    ],
  },
  {
    slug: "prometheus",
    title: "Prometheus",
    icon: "Prometheus",
    package: "prometheus-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Query Prometheus metrics with PromQL. Use for investigating performance and alert conditions.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://prometheus.io",
    authNote: "Requires the Prometheus server URL. Add auth if your deployment requires it.",
    tools: [
      { name: "query", description: "Runs an instant PromQL query.", readOnly: true, params: { query: req("PromQL expression.") } },
      { name: "query_range", description: "Runs a PromQL query over a time range.", readOnly: true, params: { query: req("PromQL expression."), start: req("Start time."), end: req("End time."), step: opt("Resolution step, such as 1m.") } },
      { name: "list_metrics", description: "Lists available metric names.", readOnly: true },
      { name: "list_alerts", description: "Lists currently firing alerts.", readOnly: true },
    ],
  },
  {
    slug: "dynatrace",
    title: "Dynatrace",
    icon: "Dynatrace",
    package: "@dynatrace-oss/dynatrace-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Query Dynatrace problems, traces and metrics. Use for root cause analysis across a monitored estate.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://dynatrace.com",
    authNote: "Requires a Dynatrace environment URL and API token with read scopes.",
    tools: [
      { name: "list_problems", description: "Lists open and recent problems.", readOnly: true, params: { from: opt("Start of time range.") } },
      { name: "get_problem", description: "Returns a problem with affected entities and root cause.", readOnly: true, params: { problem_id: req("Problem identifier.") } },
      { name: "query_metrics", description: "Queries a metric selector over a time range.", readOnly: true, params: { selector: req("Metric selector."), from: opt("Start time."), to: opt("End time.") } },
    ],
  },
  {
    slug: "heroku",
    title: "Heroku",
    icon: "Heroku",
    package: "@heroku/mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Manage Heroku apps, dynos, config and logs. Use for deployment checks and incident response.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://heroku.com",
    authNote: "Requires a Heroku API key. Scale and restart operations affect running services.",
    tools: [
      { name: "list_apps", description: "Lists apps the account can reach.", readOnly: true },
      { name: "get_logs", description: "Returns recent log output for an app.", readOnly: true, params: { app: req("App name."), lines: optNum("Number of lines.") } },
      { name: "list_dynos", description: "Lists dynos with size and state.", readOnly: true, params: { app: req("App name.") } },
      { name: "restart_dynos", description: "Restarts an app's dynos. Causes brief downtime.", params: { app: req("App name.") } },
    ],
  },
  {
    slug: "digitalocean",
    title: "DigitalOcean",
    icon: "DigitalOcean",
    package: "@digitalocean/mcp",
    category: "Cloud & DevOps",
    summary:
      "Manage DigitalOcean droplets, databases and app platform deployments. Use for infrastructure operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://digitalocean.com",
    authNote: "Requires a DigitalOcean personal access token. Create operations incur cost.",
    tools: [
      { name: "list_droplets", description: "Lists droplets with size, region and status.", readOnly: true },
      { name: "list_apps", description: "Lists App Platform apps and deployment status.", readOnly: true },
      { name: "get_app_logs", description: "Returns logs for an app deployment.", readOnly: true, params: { app_id: req("App identifier.") } },
      { name: "list_databases", description: "Lists managed database clusters.", readOnly: true },
    ],
  },
  {
    slug: "railway",
    title: "Railway",
    icon: "Railway",
    package: "@railway/mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Manage Railway projects, services and deployments. Use for checking deploys and reading service logs.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://railway.app",
    authNote: "Requires a Railway API token.",
    tools: [
      { name: "list_projects", description: "Lists projects and their services.", readOnly: true },
      { name: "get_deployments", description: "Lists recent deployments with status.", readOnly: true, params: { service_id: req("Service identifier.") } },
      { name: "get_logs", description: "Returns logs for a deployment.", readOnly: true, params: { deployment_id: req("Deployment identifier.") } },
    ],
  },
  {
    slug: "render",
    title: "Render",
    icon: "Render",
    package: "render-mcp-server",
    category: "Cloud & DevOps",
    summary:
      "Inspect Render services, deploys and logs. Use for deployment status and debugging failed builds.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://render.com",
    authNote: "Requires a Render API key.",
    tools: [
      { name: "list_services", description: "Lists services with type and status.", readOnly: true },
      { name: "list_deploys", description: "Lists deploys for a service.", readOnly: true, params: { service_id: req("Service identifier.") } },
      { name: "get_logs", description: "Returns recent logs for a service.", readOnly: true, params: { service_id: req("Service identifier."), limit: optNum("Maximum lines.") } },
    ],
  },
  {
    slug: "netlify",
    title: "Netlify",
    icon: "Netlify",
    package: "netlify-mcp",
    category: "Cloud & DevOps",
    summary:
      "Manage Netlify sites, deploys and environment variables. Use for frontend deployment operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://netlify.com",
    authNote: "Requires a Netlify personal access token.",
    tools: [
      { name: "list_sites", description: "Lists sites with their production URL.", readOnly: true },
      { name: "list_deploys", description: "Lists deploys for a site with status.", readOnly: true, params: { site_id: req("Site identifier.") } },
      { name: "get_deploy_log", description: "Returns the build log for a deploy.", readOnly: true, params: { deploy_id: req("Deploy identifier.") } },
    ],
  },
  {
    slug: "firebase",
    title: "Firebase",
    icon: "Firebase",
    package: "firebase-mcp",
    category: "Cloud & DevOps",
    summary:
      "Query Firestore, inspect authentication users and manage Firebase storage. Use for app backend operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://firebase.google.com",
    authNote: "Requires a service account key. Scope it to the minimum roles needed.",
    tools: [
      { name: "firestore_query", description: "Queries a Firestore collection.", readOnly: true, params: { collection: req("Collection path."), where: opt("Filter as JSON."), limit: optNum("Maximum documents.") } },
      { name: "get_user", description: "Returns an authentication user by uid or email.", readOnly: true, params: { identifier: req("User uid or email address.") } },
      { name: "list_storage_files", description: "Lists files in a storage bucket path.", readOnly: true, params: { path: opt("Path prefix.") } },
    ],
  },

  /* --------------------------------------------------- security & identity */
  {
    slug: "sonarqube",
    title: "SonarQube",
    icon: "SonarQube",
    package: "sonarqube-mcp-server",
    category: "Security",
    summary:
      "Read SonarQube issues, hotspots and quality gates. Use for code quality review and security triage.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://sonarsource.com",
    authNote: "Requires a SonarQube URL and user token.",
    tools: [
      { name: "list_issues", description: "Lists issues for a project, filtered by severity or type.", readOnly: true, params: { project: req("Project key."), severity: opt("Severity filter."), type: opt("BUG, VULNERABILITY or CODE_SMELL.") } },
      { name: "get_quality_gate", description: "Returns the quality gate status for a project.", readOnly: true, params: { project: req("Project key.") } },
      { name: "list_hotspots", description: "Lists security hotspots needing review.", readOnly: true, params: { project: req("Project key.") } },
    ],
  },
  {
    slug: "hackerone",
    title: "HackerOne",
    icon: "HackerOne",
    package: "hackerone-mcp",
    category: "Security",
    summary:
      "Read HackerOne reports and program activity. Use for vulnerability disclosure triage.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://hackerone.com",
    authNote: "Requires a HackerOne API identifier and token.",
    tools: [
      { name: "list_reports", description: "Lists reports for a program, filtered by state.", readOnly: true, params: { program: req("Program handle."), state: opt("Report state filter.") } },
      { name: "get_report", description: "Returns a report with its timeline and severity.", readOnly: true, params: { report_id: req("Report identifier.") } },
    ],
  },
  {
    slug: "okta",
    title: "Okta",
    icon: "Okta",
    package: "okta-mcp-server",
    category: "Security",
    summary:
      "Inspect Okta users, groups, applications and system logs. Use for access reviews and login troubleshooting.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://okta.com",
    authNote: "Requires an Okta domain and API token. Use a read-only admin role.",
    tools: [
      { name: "list_users", description: "Searches users in the directory.", readOnly: true, params: { query: opt("Search text."), limit: optNum("Maximum users.") } },
      { name: "list_groups", description: "Lists groups and their membership counts.", readOnly: true },
      { name: "get_system_logs", description: "Returns recent authentication and admin events.", readOnly: true, params: { filter: opt("Event filter expression."), since: opt("Start time, ISO 8601.") } },
      { name: "list_applications", description: "Lists assigned applications and their sign-on modes.", readOnly: true },
    ],
  },
  {
    slug: "keycloak",
    title: "Keycloak",
    icon: "Keycloak",
    package: "keycloak-mcp",
    category: "Security",
    summary:
      "Manage Keycloak realms, clients and users. Use for self-hosted identity administration and debugging.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://keycloak.org",
    authNote: "Requires a Keycloak URL and admin credentials. Restrict the service account's realm roles.",
    tools: [
      { name: "list_realms", description: "Lists realms on the server.", readOnly: true },
      { name: "list_clients", description: "Lists clients in a realm.", readOnly: true, params: { realm: req("Realm name.") } },
      { name: "search_users", description: "Searches users in a realm.", readOnly: true, params: { realm: req("Realm name."), query: opt("Search text.") } },
      { name: "get_user_sessions", description: "Returns active sessions for a user.", readOnly: true, params: { realm: req("Realm name."), user_id: req("User identifier.") } },
    ],
  },
  {
    slug: "vault",
    title: "Vault",
    icon: "Vault",
    package: "vault-mcp-server",
    category: "Security",
    summary:
      "Read HashiCorp Vault secrets metadata and audit policy. Use for secret inventory and access review.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://vaultproject.io",
    authNote: "Requires a Vault address and token. Grant a policy limited to metadata where possible.",
    tools: [
      { name: "list_secrets", description: "Lists secret paths under a mount. Returns names, not values.", readOnly: true, params: { mount: req("Secret engine mount path."), path: opt("Path prefix.") } },
      { name: "get_secret_metadata", description: "Returns version history and timestamps for a secret.", readOnly: true, params: { mount: req("Mount path."), path: req("Secret path.") } },
      { name: "list_policies", description: "Lists policies defined on the server.", readOnly: true },
    ],
  },

  /* -------------------------------------------------- research & knowledge */
  {
    slug: "wikipedia",
    title: "Wikipedia",
    icon: "Wikipedia",
    package: "wikipedia-mcp",
    category: "Research & Knowledge",
    summary:
      "Search and read Wikipedia articles. Use for background on unfamiliar topics and factual grounding.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://wikipedia.org",
    authNote: "No credentials required.",
    tools: [
      { name: "search", description: "Searches Wikipedia article titles and content.", readOnly: true, params: { query: req("Search text."), limit: optNum("Maximum results.") } },
      { name: "get_article", description: "Returns an article's text.", readOnly: true, params: { title: req("Article title.") } },
      { name: "get_summary", description: "Returns the lead section of an article.", readOnly: true, params: { title: req("Article title.") } },
    ],
  },
  {
    slug: "arxiv",
    title: "arXiv",
    icon: "arXiv",
    package: "arxiv-mcp-server",
    category: "Healthcare & Science",
    summary:
      "Search and read arXiv preprints. Use for literature review in physics, mathematics and computer science.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://arxiv.org",
    authNote: "No credentials required. Respect arXiv's rate limits.",
    tools: [
      { name: "search_papers", description: "Searches arXiv by query, author or category.", readOnly: true, params: { query: req("Search text."), category: opt("arXiv category, such as cs.LG."), max_results: optNum("Maximum papers.") } },
      { name: "get_paper", description: "Returns a paper's abstract and metadata.", readOnly: true, params: { arxiv_id: req("arXiv identifier.") } },
      { name: "download_paper", description: "Downloads a paper's full text for reading.", params: { arxiv_id: req("arXiv identifier.") } },
    ],
  },
  {
    slug: "pubmed",
    title: "PubMed",
    icon: "PubMed",
    package: "pubmed-mcp",
    category: "Healthcare & Science",
    summary:
      "Search PubMed for biomedical literature. Use for clinical and life sciences research.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://pubmed.ncbi.nlm.nih.gov",
    authNote: "No credentials required, though an NCBI API key raises rate limits.",
    tools: [
      { name: "search", description: "Searches PubMed with a query.", readOnly: true, params: { query: req("Search text or MeSH terms."), max_results: optNum("Maximum results.") } },
      { name: "get_abstract", description: "Returns a publication's abstract and metadata.", readOnly: true, params: { pmid: req("PubMed identifier.") } },
    ],
  },
  {
    slug: "zotero",
    title: "Zotero",
    icon: "Zotero",
    package: "zotero-mcp",
    category: "Research & Knowledge",
    summary:
      "Search a Zotero reference library and read annotations. Use for managing citations during research.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://zotero.org",
    authNote: "Requires a Zotero API key and user or group library id.",
    tools: [
      { name: "search_items", description: "Searches the library by title, author or tag.", readOnly: true, params: { query: req("Search text.") } },
      { name: "get_item", description: "Returns an item's full metadata and notes.", readOnly: true, params: { item_key: req("Item key.") } },
      { name: "list_collections", description: "Lists collections in the library.", readOnly: true },
    ],
  },
  {
    slug: "obsidian",
    title: "Obsidian",
    icon: "Obsidian",
    package: "mcp-obsidian",
    category: "Research & Knowledge",
    summary:
      "Read and search an Obsidian vault. Use for retrieving personal or team notes and linked knowledge.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://obsidian.md",
    authNote: "Reads a local vault directory. Point it only at vaults you want the agent to see.",
    tools: [
      { name: "search_notes", description: "Searches note content across the vault.", readOnly: true, params: { query: req("Search text.") } },
      { name: "read_note", description: "Returns a note's markdown content.", readOnly: true, params: { path: req("Note path within the vault.") } },
      { name: "list_notes", description: "Lists notes, optionally under a folder.", readOnly: true, params: { folder: opt("Folder path.") } },
    ],
  },
  {
    slug: "reddit",
    title: "Reddit",
    icon: "Reddit",
    package: "mcp-server-reddit",
    category: "Research & Knowledge",
    summary:
      "Read Reddit posts and comments. Use for community sentiment and finding discussion of a problem.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://reddit.com",
    authNote: "Reads public content. Reddit rate limits unauthenticated requests.",
    tools: [
      { name: "get_subreddit_posts", description: "Returns posts from a subreddit.", readOnly: true, params: { subreddit: req("Subreddit name without r/."), sort: opt("hot, new or top."), limit: optNum("Maximum posts.") } },
      { name: "search", description: "Searches Reddit for posts matching a query.", readOnly: true, params: { query: req("Search text."), subreddit: opt("Restrict to one subreddit.") } },
      { name: "get_comments", description: "Returns the comment thread for a post.", readOnly: true, params: { post_id: req("Post identifier.") } },
    ],
  },
  {
    slug: "youtube",
    title: "YouTube",
    icon: "YouTube",
    package: "youtube-mcp-server",
    category: "Research & Knowledge",
    summary:
      "Search YouTube and read video transcripts. Use for extracting content from talks and tutorials.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://youtube.com",
    authNote: "Requires a YouTube Data API key for search; transcripts may work without one.",
    tools: [
      { name: "search_videos", description: "Searches for videos by query.", readOnly: true, params: { query: req("Search text."), limit: optNum("Maximum results.") } },
      { name: "get_transcript", description: "Returns a video's transcript.", readOnly: true, params: { video_id: req("Video identifier.") } },
      { name: "get_video_details", description: "Returns a video's title, channel and statistics.", readOnly: true, params: { video_id: req("Video identifier.") } },
    ],
  },
  {
    slug: "brave-search",
    title: "Brave Search",
    icon: "Brave",
    package: "@brave/brave-search-mcp-server",
    category: "Research & Knowledge",
    summary:
      "Search the web with Brave's independent index. Use for privacy-respecting search with structured results.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://brave.com/search/api",
    authNote: "Requires a Brave Search API key. A free tier is available.",
    tools: [
      { name: "brave_web_search", description: "Searches the web and returns ranked results.", readOnly: true, params: { query: req("Search text."), count: optNum("Maximum results.") } },
      { name: "brave_news_search", description: "Searches recent news.", readOnly: true, params: { query: req("Search text."), count: optNum("Maximum results.") } },
    ],
  },
  {
    slug: "perplexity",
    title: "Perplexity",
    icon: "Perplexity",
    package: "@perplexity-ai/mcp-server",
    category: "Research & Knowledge",
    summary:
      "Ask Perplexity for cited, synthesised answers. Use when a question needs current sources rather than raw links.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://perplexity.ai",
    authNote: "Requires a Perplexity API key. Requests are billed per token.",
    tools: [
      { name: "ask", description: "Asks a question and returns an answer with citations.", readOnly: true, params: { query: req("Question text."), model: opt("Model name to use.") } },
    ],
  },

  /* -------------------------------------------------------- AI & tooling */
  {
    slug: "hugging-face",
    title: "Hugging Face",
    icon: "Hugging Face",
    package: "@llmindset/mcp-hfspace",
    category: "AI & Accelerated Computing",
    summary:
      "Call Hugging Face Spaces as tools. Use to run hosted models for images, audio and text without local GPUs.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://huggingface.co",
    authNote: "A Hugging Face token is needed for private or rate-limited Spaces.",
    tools: [
      { name: "list_spaces", description: "Lists configured Spaces available as tools.", readOnly: true },
      { name: "call_space", description: "Runs a Space with the given inputs. May incur compute cost.", params: { space: req("Space identifier, such as owner/name."), inputs: req("Inputs as JSON matching the Space's signature.") } },
    ],
  },
  {
    slug: "openai",
    title: "OpenAI",
    icon: "OpenAI",
    package: "openai-mcp-server",
    category: "AI & Accelerated Computing",
    summary:
      "Call OpenAI models for completion, embeddings and images. Use for delegating a subtask to a specific model.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://openai.com",
    authNote: "Requires an OpenAI API key. Calls are billed per token.",
    tools: [
      { name: "list_models", description: "Lists models available to the key.", readOnly: true },
      { name: "create_completion", description: "Generates a completion. Billed per token.", params: { model: req("Model name."), prompt: req("Prompt text."), max_tokens: optNum("Maximum tokens to generate.") } },
      { name: "create_embedding", description: "Returns an embedding vector for text. Billed per token.", params: { model: req("Embedding model name."), input: req("Text to embed.") } },
    ],
  },
  {
    slug: "replicate",
    title: "Replicate",
    icon: "Replicate",
    package: "replicate-mcp",
    category: "AI & Accelerated Computing",
    summary:
      "Run models hosted on Replicate. Use for image generation, upscaling and specialised model inference.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://replicate.com",
    authNote: "Requires a Replicate API token. Predictions are billed by runtime.",
    tools: [
      { name: "search_models", description: "Searches available models.", readOnly: true, params: { query: req("Search text.") } },
      { name: "run_prediction", description: "Runs a model and returns its output. Billed by runtime.", params: { model: req("Model identifier, such as owner/name."), input: req("Model inputs as JSON.") } },
      { name: "get_prediction", description: "Returns the status and output of a prediction.", readOnly: true, params: { prediction_id: req("Prediction identifier.") } },
    ],
  },
  {
    slug: "puppeteer",
    title: "Puppeteer",
    icon: "Puppeteer",
    package: "@modelcontextprotocol/server-puppeteer",
    category: "Tools & Automation",
    summary:
      "Control a headless Chrome instance. Use for scraping rendered pages and generating PDFs.",
    auth: "none",
    scopes: ["read", "write"],
    homepage: "https://pptr.dev",
    authNote: "Runs Chromium locally. Only browse sites you are permitted to automate.",
    tools: [
      { name: "navigate", description: "Opens a URL.", params: { url: req("Destination URL.") } },
      { name: "get_content", description: "Returns the rendered HTML of the page.", readOnly: true },
      { name: "click", description: "Clicks an element by selector.", params: { selector: req("CSS selector.") } },
      { name: "screenshot", description: "Captures a screenshot.", readOnly: true, params: { full_page: opt("true to capture the whole page.") } },
    ],
  },
  {
    slug: "git",
    title: "Git",
    icon: "Git",
    package: "mcp-server-git",
    category: "Software Engineering",
    summary:
      "Read local Git history, diffs and branches. Use for understanding how code reached its current state.",
    auth: "none",
    scopes: ["read"],
    homepage: "https://git-scm.com",
    authNote: "Operates on a local repository path you specify.",
    tools: [
      { name: "git_log", description: "Returns commit history for a path or branch.", readOnly: true, params: { path: opt("File or directory to filter by."), max_count: optNum("Maximum commits.") } },
      { name: "git_diff", description: "Returns the diff between two refs.", readOnly: true, params: { from: req("Base ref."), to: opt("Target ref, defaults to working tree.") } },
      { name: "git_show", description: "Returns a commit's message and changes.", readOnly: true, params: { commit: req("Commit hash or ref.") } },
      { name: "git_blame", description: "Returns line-by-line authorship for a file.", readOnly: true, params: { path: req("File path.") } },
    ],
  },

  /* ------------------------------------------- content, design & analytics */
  {
    slug: "contentful",
    title: "Contentful",
    icon: "Contentful",
    package: "@contentful/mcp-server",
    category: "Documents & Communication",
    summary:
      "Read and update Contentful entries and content types. Use for headless CMS content operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://contentful.com",
    authNote: "Requires a Contentful management token and space id.",
    tools: [
      { name: "list_entries", description: "Lists entries of a content type.", readOnly: true, params: { content_type: opt("Content type id."), limit: optNum("Maximum entries.") } },
      { name: "get_entry", description: "Returns an entry with all its fields.", readOnly: true, params: { entry_id: req("Entry identifier.") } },
      { name: "list_content_types", description: "Lists content types and their fields.", readOnly: true },
      { name: "publish_entry", description: "Publishes an entry, making it live.", params: { entry_id: req("Entry identifier.") } },
    ],
  },
  {
    slug: "sanity",
    title: "Sanity",
    icon: "Sanity",
    package: "@sanity/mcp-server",
    category: "Documents & Communication",
    summary:
      "Query and update Sanity content with GROQ. Use for structured content management.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://sanity.io",
    authNote: "Requires a Sanity project id, dataset and API token.",
    tools: [
      { name: "query", description: "Runs a GROQ query against the dataset.", readOnly: true, params: { groq: req("GROQ query.") } },
      { name: "get_document", description: "Returns a document by id.", readOnly: true, params: { document_id: req("Document identifier.") } },
      { name: "create_document", description: "Creates a document.", params: { type: req("Document type."), fields: req("Field values as JSON.") } },
    ],
  },
  {
    slug: "canva",
    title: "Canva",
    icon: "Canva",
    package: "@canva/cli",
    category: "Design & Creative",
    summary:
      "Work with Canva designs and assets. Use for generating and exporting branded visual content.",
    auth: "oauth2",
    scopes: ["read", "write"],
    homepage: "https://canva.com",
    authNote: "Authenticates against your Canva account via OAuth.",
    tools: [
      { name: "list_designs", description: "Lists designs in the account.", readOnly: true, params: { limit: optNum("Maximum designs.") } },
      { name: "get_design", description: "Returns a design's metadata and pages.", readOnly: true, params: { design_id: req("Design identifier.") } },
      { name: "export_design", description: "Exports a design to an image or PDF.", params: { design_id: req("Design identifier."), format: opt("png, jpg or pdf.") } },
    ],
  },
  {
    slug: "posthog",
    title: "PostHog",
    icon: "PostHog",
    package: "@posthog/mcp",
    category: "Data & Analytics",
    summary:
      "Query PostHog events, funnels and feature flags. Use for product analytics and experiment results.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://posthog.com",
    authNote: "Requires a PostHog personal API key and project id.",
    tools: [
      { name: "query_events", description: "Queries events with filters over a time range.", readOnly: true, params: { event: opt("Event name."), after: opt("Start time."), limit: optNum("Maximum events.") } },
      { name: "get_insight", description: "Returns a saved insight's current result.", readOnly: true, params: { insight_id: req("Insight identifier.") } },
      { name: "list_feature_flags", description: "Lists feature flags and rollout percentages.", readOnly: true },
    ],
  },
  {
    slug: "mixpanel",
    title: "Mixpanel",
    icon: "Mixpanel",
    package: "mixpanel-mcp",
    category: "Data & Analytics",
    summary:
      "Query Mixpanel events and funnels. Use for product usage analysis and retention reporting.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://mixpanel.com",
    authNote: "Requires a Mixpanel service account and project id.",
    tools: [
      { name: "query_events", description: "Returns event counts over a period.", readOnly: true, params: { event: req("Event name."), from_date: req("Start date."), to_date: req("End date.") } },
      { name: "get_funnel", description: "Returns conversion rates for a saved funnel.", readOnly: true, params: { funnel_id: req("Funnel identifier.") } },
      { name: "get_retention", description: "Returns a retention cohort table.", readOnly: true, params: { from_date: req("Start date."), to_date: req("End date.") } },
    ],
  },
  {
    slug: "metabase",
    title: "Metabase",
    icon: "Metabase",
    package: "@cognitionai/metabase-mcp-server",
    category: "Data & Analytics",
    summary:
      "Run Metabase questions and browse dashboards. Use for self-service analytics over an existing BI setup.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://metabase.com",
    authNote: "Requires a Metabase URL and API key.",
    tools: [
      { name: "list_dashboards", description: "Lists dashboards and their cards.", readOnly: true },
      { name: "run_card", description: "Runs a saved question and returns rows.", readOnly: true, params: { card_id: req("Card identifier.") } },
      { name: "list_databases", description: "Lists connected databases and schemas.", readOnly: true },
    ],
  },
  {
    slug: "google-sheets",
    title: "Google Sheets",
    icon: "Google Sheets",
    package: "google-sheets-mcp",
    category: "Data & Analytics",
    summary:
      "Read and write Google Sheets. Use for lightweight shared data, trackers and report exports.",
    auth: "oauth2",
    scopes: ["read", "write"],
    homepage: "https://sheets.google.com",
    authNote: "Requires Google OAuth credentials with the Sheets scope.",
    tools: [
      { name: "read_range", description: "Reads values from a range.", readOnly: true, params: { spreadsheet_id: req("Spreadsheet identifier."), range: req("A1 notation range.") } },
      { name: "write_range", description: "Writes values to a range, overwriting existing cells.", params: { spreadsheet_id: req("Spreadsheet identifier."), range: req("A1 notation range."), values: req("Rows as a JSON array of arrays.") } },
      { name: "append_row", description: "Appends a row to a sheet.", params: { spreadsheet_id: req("Spreadsheet identifier."), range: req("Sheet or range to append to."), values: req("Row values as a JSON array.") } },
    ],
  },
  {
    slug: "google-docs",
    title: "Google Docs",
    icon: "Google Docs",
    package: "google-docs-mcp",
    category: "Documents & Communication",
    summary:
      "Read and edit Google Docs. Use for drafting, reviewing and extracting document content.",
    auth: "oauth2",
    scopes: ["read", "write"],
    homepage: "https://docs.google.com",
    authNote: "Requires Google OAuth credentials with the Docs scope.",
    tools: [
      { name: "read_document", description: "Returns a document's text content.", readOnly: true, params: { document_id: req("Document identifier.") } },
      { name: "create_document", description: "Creates a document with optional content.", params: { title: req("Document title."), content: opt("Initial body text.") } },
      { name: "append_text", description: "Appends text to the end of a document.", params: { document_id: req("Document identifier."), text: req("Text to append.") } },
    ],
  },
  {
    slug: "google-maps",
    title: "Google Maps",
    icon: "Google Maps",
    package: "@modelcontextprotocol/server-google-maps",
    category: "Tools & Automation",
    summary:
      "Geocode addresses, search places and get directions. Use for location lookups and travel planning.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://maps.google.com",
    authNote: "Requires a Google Maps Platform API key. Requests are billed.",
    tools: [
      { name: "geocode", description: "Converts an address to coordinates.", readOnly: true, params: { address: req("Address text.") } },
      { name: "search_places", description: "Searches for places near a location.", readOnly: true, params: { query: req("Search text."), location: opt("Latitude,longitude to search near.") } },
      { name: "get_directions", description: "Returns a route between two points.", readOnly: true, params: { origin: req("Start address or coordinates."), destination: req("End address or coordinates."), mode: opt("driving, walking or transit.") } },
    ],
  },
  {
    slug: "mapbox",
    title: "Mapbox",
    icon: "Mapbox",
    package: "@mapbox/mcp-server",
    category: "Tools & Automation",
    summary:
      "Geocode, route and query map data with Mapbox. Use for location intelligence and map generation.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://mapbox.com",
    authNote: "Requires a Mapbox access token. Requests count against your quota.",
    tools: [
      { name: "geocode", description: "Converts a place name to coordinates.", readOnly: true, params: { query: req("Place or address text.") } },
      { name: "reverse_geocode", description: "Converts coordinates to a place name.", readOnly: true, params: { longitude: req("Longitude."), latitude: req("Latitude.") } },
      { name: "get_directions", description: "Returns a route with distance and duration.", readOnly: true, params: { coordinates: req("Semicolon-separated lon,lat pairs."), profile: opt("driving, walking or cycling.") } },
    ],
  },
  {
    slug: "todoist",
    title: "Todoist",
    icon: "Todoist",
    package: "@doist/todoist-mcp",
    category: "Documents & Communication",
    summary:
      "Manage Todoist tasks and projects. Use for personal and team task tracking.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://todoist.com",
    authNote: "Requires a Todoist API token.",
    tools: [
      { name: "list_tasks", description: "Lists active tasks, optionally filtered.", readOnly: true, params: { filter: opt("Todoist filter query, such as today.") } },
      { name: "create_task", description: "Creates a task.", params: { content: req("Task text."), due_string: opt("Natural language due date."), project_id: opt("Project identifier.") } },
      { name: "complete_task", description: "Marks a task complete.", params: { task_id: req("Task identifier.") } },
      { name: "list_projects", description: "Lists projects.", readOnly: true },
    ],
  },
  {
    slug: "clickup",
    title: "ClickUp",
    icon: "ClickUp",
    package: "@taazkareem/clickup-mcp-server",
    category: "Documents & Communication",
    summary:
      "Manage ClickUp tasks, lists and docs. Use for project tracking in a ClickUp workspace.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://clickup.com",
    authNote: "Requires a ClickUp personal API token.",
    tools: [
      { name: "list_tasks", description: "Lists tasks in a list with status and assignee.", readOnly: true, params: { list_id: req("List identifier."), status: opt("Filter by status.") } },
      { name: "get_task", description: "Returns a task with description and custom fields.", readOnly: true, params: { task_id: req("Task identifier.") } },
      { name: "create_task", description: "Creates a task in a list.", params: { list_id: req("List identifier."), name: req("Task title."), description: opt("Task body."), assignees: opt("Assignee ids as JSON array.") } },
      { name: "update_task", description: "Updates a task's status or fields.", params: { task_id: req("Task identifier."), status: opt("New status."), description: opt("New description.") } },
    ],
  },
  {
    slug: "dropbox",
    title: "Dropbox",
    icon: "Dropbox",
    package: "dropbox-mcp-server",
    category: "Documents & Communication",
    summary:
      "List, read and search files in Dropbox. Use for retrieving shared documents and assets.",
    auth: "oauth2",
    scopes: ["read"],
    homepage: "https://dropbox.com",
    authNote: "Requires Dropbox OAuth credentials. Grant read-only scopes where possible.",
    tools: [
      { name: "list_files", description: "Lists files and folders under a path.", readOnly: true, params: { path: opt("Folder path, or root if omitted.") } },
      { name: "search", description: "Searches files by name or content.", readOnly: true, params: { query: req("Search text.") } },
      { name: "read_file", description: "Returns a file's contents.", readOnly: true, params: { path: req("File path.") } },
    ],
  },
  {
    slug: "box",
    title: "Box",
    icon: "Box",
    package: "box-mcp-server",
    category: "Documents & Communication",
    summary:
      "Browse and read files in Box. Use for enterprise document retrieval and content search.",
    auth: "oauth2",
    scopes: ["read"],
    homepage: "https://box.com",
    authNote: "Requires Box OAuth or JWT credentials scoped to the folders you expose.",
    tools: [
      { name: "list_items", description: "Lists items in a folder.", readOnly: true, params: { folder_id: opt("Folder identifier, or root if omitted.") } },
      { name: "search", description: "Searches files by name and content.", readOnly: true, params: { query: req("Search text.") } },
      { name: "read_file", description: "Returns a file's text content.", readOnly: true, params: { file_id: req("File identifier.") } },
    ],
  },

  /*
   * Replacements for candidates Simple Icons does not carry.
   *
   * Several strong MCP servers — Qdrant, Pinecone, Playwright, Firecrawl among
   * them — have no brand mark in Simple Icons, and drawing a substitute would
   * misrepresent the brand. They were dropped in favour of equally useful
   * services whose artwork is genuinely available.
   */
  {
    slug: "meilisearch",
    title: "Meilisearch",
    icon: "Meilisearch",
    package: "meilisearch-mcp",
    category: "Data & Analytics",
    summary:
      "Search and manage Meilisearch indexes. Use for fast typo-tolerant search over application data.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://meilisearch.com",
    authNote: "Requires a Meilisearch host URL and API key.",
    tools: [
      { name: "list_indexes", description: "Lists indexes with document counts.", readOnly: true },
      { name: "search", description: "Searches an index and returns ranked hits.", readOnly: true, params: { index: req("Index name."), query: req("Search text."), limit: optNum("Maximum hits.") } },
      { name: "get_settings", description: "Returns an index's searchable and filterable attributes.", readOnly: true, params: { index: req("Index name.") } },
      { name: "add_documents", description: "Adds or replaces documents in an index.", params: { index: req("Index name."), documents: req("Documents as a JSON array.") } },
    ],
  },
  {
    slug: "temporal",
    title: "Temporal",
    icon: "Temporal",
    package: "temporal-mcp",
    category: "Cloud & DevOps",
    summary:
      "Inspect Temporal workflows and their execution history. Use for debugging long-running or stuck workflows.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://temporal.io",
    authNote: "Requires a Temporal namespace and connection credentials.",
    tools: [
      { name: "list_workflows", description: "Lists workflow executions, filtered by status.", readOnly: true, params: { query: opt("List filter query."), limit: optNum("Maximum executions.") } },
      { name: "get_workflow_history", description: "Returns the event history for one execution.", readOnly: true, params: { workflow_id: req("Workflow identifier."), run_id: opt("Run identifier.") } },
      { name: "describe_workflow", description: "Returns current status, task queue and pending activities.", readOnly: true, params: { workflow_id: req("Workflow identifier.") } },
    ],
  },
  {
    slug: "kafka",
    title: "Apache Kafka",
    icon: "Apache Kafka",
    package: "kafka-mcp-server",
    category: "Data & Analytics",
    summary:
      "Inspect Kafka topics, consumer groups and lag. Use for diagnosing streaming pipelines and backlogs.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://kafka.apache.org",
    authNote: "Requires broker addresses and, where enabled, SASL credentials.",
    tools: [
      { name: "list_topics", description: "Lists topics with partition counts.", readOnly: true },
      { name: "describe_topic", description: "Returns a topic's partitions, replicas and configuration.", readOnly: true, params: { topic: req("Topic name.") } },
      { name: "get_consumer_lag", description: "Returns consumer group offsets and lag per partition.", readOnly: true, params: { group: req("Consumer group id.") } },
      { name: "consume_messages", description: "Reads recent messages from a topic.", readOnly: true, params: { topic: req("Topic name."), limit: optNum("Maximum messages.") } },
    ],
  },
  {
    slug: "cloudinary",
    title: "Cloudinary",
    icon: "Cloudinary",
    package: "cloudinary-mcp-server",
    category: "Design & Creative",
    summary:
      "Manage and transform images and video in Cloudinary. Use for asset delivery and media pipelines.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://cloudinary.com",
    authNote: "Requires a Cloudinary cloud name, API key and secret.",
    tools: [
      { name: "search_assets", description: "Searches media assets by tag, folder or format.", readOnly: true, params: { expression: req("Search expression."), max_results: optNum("Maximum assets.") } },
      { name: "get_asset", description: "Returns an asset's metadata and delivery URL.", readOnly: true, params: { public_id: req("Asset public id.") } },
      { name: "upload_asset", description: "Uploads a file to the media library.", params: { file: req("File path or URL."), folder: opt("Destination folder.") } },
    ],
  },
  {
    slug: "webflow",
    title: "Webflow",
    icon: "Webflow",
    package: "webflow-mcp-server",
    category: "Design & Creative",
    summary:
      "Read and update Webflow sites, collections and CMS items. Use for marketing site content operations.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://webflow.com",
    authNote: "Requires a Webflow API token scoped to the sites you expose.",
    tools: [
      { name: "list_sites", description: "Lists sites the token can reach.", readOnly: true },
      { name: "list_collections", description: "Lists CMS collections for a site.", readOnly: true, params: { site_id: req("Site identifier.") } },
      { name: "list_items", description: "Lists items in a collection.", readOnly: true, params: { collection_id: req("Collection identifier."), limit: optNum("Maximum items.") } },
      { name: "create_item", description: "Creates a CMS item as draft or live.", params: { collection_id: req("Collection identifier."), fields: req("Field values as JSON."), live: opt("true to publish immediately.") } },
    ],
  },
  {
    slug: "resend",
    title: "Resend",
    icon: "Resend",
    package: "resend-mcp",
    category: "Sales & Marketing",
    summary:
      "Send transactional email and inspect delivery through Resend. Use for developer-focused email workflows.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://resend.com",
    authNote: "Requires a Resend API key and a verified sending domain.",
    tools: [
      { name: "send_email", description: "Sends an email. Delivers to real recipients.", params: { to: req("Recipient address."), from: req("Verified sender address."), subject: req("Subject line."), html: req("Message body as HTML.") } },
      { name: "get_email", description: "Returns an email's delivery status.", readOnly: true, params: { email_id: req("Email identifier.") } },
      { name: "list_domains", description: "Lists sending domains and their verification status.", readOnly: true },
    ],
  },
  {
    slug: "influxdb",
    title: "InfluxDB",
    icon: "InfluxDB",
    package: "influxdb-mcp-server",
    category: "Data & Analytics",
    summary:
      "Query InfluxDB time-series data. Use for metrics, sensor readings and operational telemetry.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://influxdata.com",
    authNote: "Requires an InfluxDB URL, organisation and API token.",
    tools: [
      { name: "list_buckets", description: "Lists buckets with retention periods.", readOnly: true },
      { name: "query", description: "Runs a Flux query and returns rows.", readOnly: true, params: { flux: req("Flux query text.") } },
      { name: "list_measurements", description: "Lists measurements in a bucket.", readOnly: true, params: { bucket: req("Bucket name.") } },
    ],
  },
  {
    slug: "gitea",
    title: "Gitea",
    icon: "Gitea",
    package: "gitea-mcp-server",
    category: "Software Engineering",
    summary:
      "Browse Gitea repositories, issues and pull requests. Use for self-hosted Git workflows.",
    auth: "apiKey",
    scopes: ["read", "write"],
    homepage: "https://gitea.io",
    authNote: "Requires a Gitea instance URL and access token.",
    tools: [
      { name: "list_repos", description: "Lists repositories the token can reach.", readOnly: true },
      { name: "list_issues", description: "Lists issues for a repository.", readOnly: true, params: { owner: req("Owner name."), repo: req("Repository name."), state: opt("open or closed.") } },
      { name: "get_pull_request", description: "Returns a pull request with its diff summary.", readOnly: true, params: { owner: req("Owner name."), repo: req("Repository name."), index: req("Pull request number.") } },
      { name: "create_issue", description: "Opens an issue.", params: { owner: req("Owner name."), repo: req("Repository name."), title: req("Issue title."), body: opt("Issue description.") } },
    ],
  },
  {
    slug: "opsgenie",
    title: "Opsgenie",
    icon: "Opsgenie",
    package: "opsgenie-mcp",
    category: "Cloud & DevOps",
    summary:
      "Read Opsgenie alerts and on-call schedules. Use during incidents to find who is on call and what fired.",
    auth: "apiKey",
    scopes: ["read"],
    homepage: "https://atlassian.com/software/opsgenie",
    authNote: "Requires an Opsgenie API key.",
    tools: [
      { name: "list_alerts", description: "Lists alerts, filtered by status or priority.", readOnly: true, params: { query: opt("Alert search query."), limit: optNum("Maximum alerts.") } },
      { name: "get_alert", description: "Returns an alert with its notes and timeline.", readOnly: true, params: { alert_id: req("Alert identifier.") } },
      { name: "who_is_on_call", description: "Returns the current on-call responders for a schedule.", readOnly: true, params: { schedule: req("Schedule name or identifier.") } },
    ],
  },
];
