/**
 * Domain skills for the roles the original catalogue never reached.
 *
 * ## Why a second data file
 *
 * `skills.data.mjs` holds the first 72 and is generated by `gen-skills.mjs`. Splitting rather than
 * appending keeps that file reviewable and makes this batch's provenance obvious: these were written
 * against a measured coverage gap, not added opportunistically.
 *
 * ## The gap they close
 *
 * `skillsForRole` routes a skill to an agent by shared meaningful word between the agent's role and
 * the skill's declared `roles`, plus `ROLE_SYNONYMS`, minus generic seniority words. Measured against
 * the real matcher, **84 of the 165 roles matched no skill at all** — every accountant, every baker,
 * every producer, every event planner. Those agents were running on their one-line role description.
 *
 * Worst first: Accounting & Tax had 8 of 8 uncovered, Media & Communications 7 of 7, Retail and
 * Hospitality 6 each.
 *
 * ## What makes these worth loading
 *
 * The same standard as the existing skills: specific, opinionated, about the trade-offs a
 * practitioner actually faces. A skill that lists definitions is worse than no skill, because it
 * spends context to tell a model what it already knows.
 *
 * `roles` must name **exact role strings from the agent catalogue** (`Backend/src/data/agentCatalog.ts`).
 * A near-miss means the skill is silently invisible, which is the failure mode this batch exists to
 * fix.
 */

export const DOMAIN_SKILLS = [
  /* ------------------------------------------------- Accounting, Tax & Audit */
  {
    name: "month-end-close",
    category: "Data & Analytics",
    roles: ["Chartered Accountant", "Senior Accountant", "Management Accountant", "Junior Accountant"],
    description:
      "Closes the books predictably and finds the number that is wrong. Use when a close is late, a balance will not reconcile, or the same adjustment keeps recurring.",
    body: `
# Month-end Close

## A close is a deadline, not a search

The purpose is a set of numbers someone can act on by a known date. A close that produces perfect figures two weeks late has failed at its actual job, because the decisions it was meant to inform were already made.

So work to materiality. An unexplained fifty on a six-figure ledger is noise; chasing it while revenue recognition is unreviewed is the wrong order every time.

## Reconcile from the outside in

Start with the accounts an external party can confirm: bank, merchant processor, payroll provider, tax authority. Those balances are facts. Anything reconciled against your own subledger only proves your ledger agrees with itself.

Every reconciliation names its difference. "Timing" is not an explanation — "three deposits cleared on the 2nd" is.

## Accruals are a policy, not a judgement call

Decide the threshold and the estimation method once, write it down, and apply it. Accruals decided fresh each month become the lever by which the result is quietly managed, whether or not anyone intends that.

An accrual you cannot explain to an auditor next quarter should not be posted this quarter.

## The variance is the deliverable

Nobody reads a balanced trial balance. They read why gross margin moved two points. Investigate the largest movements against both prior month and budget, and state cause rather than restating the number.

If a movement has no cause you can name, say so plainly. An invented explanation is worse than an open question, because it stops anyone looking.

## Watch out for

- Manual journals with no supporting document, especially recurring ones.
- Suspense and clearing accounts that never empty — they hide errors indefinitely.
- Prepayments and deferred revenue amortising on a schedule nobody has checked against the contract.
- A close that depends on one person's spreadsheet and undocumented knowledge.
- Round-number adjustments, which are almost always a plug rather than a calculation.

## Finishing

Every balance-sheet account is reconciled or explicitly explained. Material variances have named causes. The next close could be run by someone else from the notes.
`,
  },
  {
    name: "tax-filing-preparation",
    category: "Data & Analytics",
    roles: ["Tax Consultant", "Chartered Accountant", "Senior Accountant", "Management Accountant"],
    description:
      "Prepares a filing that survives review, and separates the settled from the arguable. Use when preparing a return, answering a notice, or deciding how aggressive a position should be.",
    body: `
# Tax Filing Preparation

## Two different things wear the same word

A **rule** is what the statute says. A **position** is what you argue when the statute does not clearly say. Conflating them is how a filing becomes indefensible: the reviewer discovers the confident sentence was an interpretation.

State which is which. "Deductible under s.37" and "we treat this as revenue expenditure because the benefit does not extend beyond the year" are different sentences with different risks.

## The deadline is not the constraint people think

Late filing is a known, priced penalty. An incorrect filing is an open liability with interest, and it resets attention on prior years. Where you cannot get a number right in time, prefer the extension or the estimated payment over the confident guess.

## Reconcile the return to the accounts

Every figure on a return should trace to a ledger balance plus a named adjustment. Book-to-tax differences are the whole substance of the work: depreciation, provisions, disallowed expenses, timing.

A return that cannot be tied back to the trial balance will not survive the first question about it.

## Never state a rate or a deadline from memory

Thresholds, rates and due dates change, and they change by jurisdiction and by entity type. Look them up for the specific year and entity, every time, and cite where you looked.

This is the single most common way tax work goes wrong, and it is entirely avoidable.

## Documentation is the deliverable

The file should let a different practitioner reach the same numbers next year. That means the workings, the source documents, the positions taken and the reason for each — not just the final schedule.

## Watch out for

- Related-party transactions without documented arm's-length reasoning.
- Personal expenditure routed through the business, which is where most disputes begin.
- Prior-year adjustments repeated because nobody read last year's file.
- Cash-basis figures used in an accrual return.
- A position taken because it was taken last year, with no one able to say why.

## Finishing

Every number traces to the accounts. Positions are labelled as positions with reasoning. Rates and dates were verified for this year, not recalled.
`,
  },
  {
    name: "audit-fieldwork",
    category: "Security",
    roles: ["Audit Manager", "Chartered Accountant", "Risk Manager", "Senior Accountant"],
    description:
      "Gathers evidence that supports a conclusion rather than a file that looks complete. Use when planning testing, sampling a population, or deciding whether a finding is material.",
    body: `
# Audit Fieldwork

## Evidence has a hierarchy, and it is not a preference

External confirmation beats a system report; a system report beats a client-prepared schedule; a client-prepared schedule beats a verbal explanation. Substituting downward without saying so is the most common defect in a working paper.

When you accept weaker evidence, record why the stronger evidence was unavailable.

## Test the control or test the balance, and know which

Controls testing asks whether the process would catch an error. Substantive testing asks whether this number is right. They answer different questions, and a controls conclusion cannot be repaired by more substantive work at the same sample size.

If controls fail, the substantive sample gets larger. That is the actual consequence, not a note in the file.

## Sampling is a claim about a population

A sample is only meaningful with a stated population, a stated method and a stated basis for the size. "Twenty invoices" is not a sample; "twenty of 4,300 payments over the threshold, selected by monetary-unit sampling" is.

Judgemental selection is legitimate and must be labelled as such, because it supports no statistical extrapolation.

## A finding needs cause, effect and extent

"Three purchase orders lacked approval" is an observation. The finding is what allowed it, what it could cost, and how much of the population is likely affected. Without extent, management cannot size the response and will reasonably discount it.

## Watch out for

- Rolling forward last year's programme without asking what changed.
- Evidence obtained from the person whose work is being tested, unverified.
- Journal entries posted outside the normal cycle or by unusual users — the highest-yield test in most audits.
- Immaterial findings crowding out a material one in the report.
- Confirming the balance you expected and stopping there.

## Finishing

Every conclusion names its evidence and its evidence's tier. Samples state population, method and size basis. Findings carry cause, effect and extent.
`,
  },
  {
    name: "payroll-operations",
    category: "Documents & Communication",
    roles: ["Payroll Specialist", "HR Coordinator", "Management Accountant", "Junior Accountant"],
    description:
      "Runs payroll correctly the first time and fixes errors without compounding them. Use when setting up a cycle, correcting an over- or underpayment, or handling a leaver mid-period.",
    body: `
# Payroll Operations

## Wrong pay is not a data problem

An underpayment is somebody's rent. An overpayment is a recovery conversation nobody wants and, in many places, one you cannot simply reverse from the next payslip without consent.

So the checks belong before the run, not in a reconciliation afterwards. Payroll is the one process where "we will correct it next cycle" is a real cost to a real person.

## Compare every run to the last one

The highest-yield control is a variance report against the previous period, line by line, per person. New starters, leavers, changed hours, changed tax codes and one-off payments should account for every difference.

A difference you cannot attribute is an error you have not found yet.

## Statutory deductions are not negotiable or memorable

Rates, thresholds, contribution bands and filing dates change by year and jurisdiction. Look them up for the period being run. Never carry a rate forward because it was right last quarter.

## Corrections have a right order

Establish the correct gross first, then the correct deductions, then the difference to pay or recover, then the statutory correction filing. Adjusting net pay directly leaves the deduction records wrong, which surfaces months later as a mismatch with the authority.

Tell the person before the money moves. Every time.

## Watch out for

- A leaver paid a full period, or a starter missed entirely, because the cutoff was ambiguous.
- Backdated pay rises spanning a tax-year boundary.
- Benefits in kind and expense reimbursements treated as the same thing.
- Bank details changed shortly before a run — a common fraud pattern, and worth a call-back to a known number.
- One person holding the whole process with no documented runbook.

## Finishing

Every variance from last period is attributed. Statutory rates were verified for this period. Anyone affected by a correction was told before it happened.
`,
  },
  {
    name: "accounts-payable-control",
    category: "Tools & Automation",
    roles: ["Accounts Payable Specialist", "Junior Accountant", "Procurement Specialist", "Bookkeeping Assistant"],
    description:
      "Pays the right supplier the right amount once. Use when setting up an approval flow, handling a disputed invoice, or investigating a duplicate or suspicious payment.",
    body: `
# Accounts Payable Control

## Three-way match, and why it is not bureaucracy

Purchase order, goods received note, invoice. Each answers a different question: was it authorised, did it arrive, is this what we agreed to pay. Skipping any one of them is how a business pays for things it did not order or did not receive.

Where a match is impossible — services, subscriptions — name the substitute control rather than waiving the requirement silently.

## Segregation is the control that actually works

Whoever creates a supplier must not be whoever approves a payment. Most payment fraud is a new bank account on an existing supplier, and that single separation defeats it.

Verify bank-detail changes by calling a number you already held, never one from the request itself.

## Duplicates are structural, not careless

The same invoice arrives by email and by post, or with a leading zero dropped, or split across two POs. Detection keys on supplier plus amount plus date and near-matches of the reference — not exact-match on the invoice number, which is what lets them through.

## A payment run is a decision about cash, not a task

Prioritise by consequence: statutory obligations, then supply-critical suppliers, then everything else. Take the early-settlement discount when it beats the cost of the cash, and say so with the arithmetic.

Sitting on an invoice without telling the supplier is a decision too — an expensive one, in goodwill.

## Watch out for

- Round-sum invoices with vague descriptions from suppliers nobody recognises.
- Approval thresholds that are just below the level requiring a second signature.
- Credit notes not applied, so the balance is paid twice over.
- Statements never reconciled to the ledger, hiding both missing invoices and duplicates.
- Urgency as a pressure tactic. Genuine urgency survives a verification call.

## Finishing

Every payment traces to an authorisation and a receipt or a named substitute control. Bank changes were verified independently. Duplicate checks ran on near-matches, not exact ones.
`,
  },

  /* ---------------------------------------------- Food, Bakery & Hospitality */
  {
    name: "recipe-costing-and-yield",
    category: "Data & Analytics",
    roles: ["Head Baker", "Pastry Chef", "Baker", "Junior Baker", "Food Cost Analyst", "Restaurant General Manager"],
    description:
      "Prices a menu item from what it actually costs to make, including what gets thrown away. Use when setting prices, a margin has slipped, or a recipe is being scaled.",
    body: `
# Recipe Costing and Yield

## Yield is where the money is, not the ingredient list

A recipe costed from raw purchase weight is wrong by whatever gets trimmed, evaporated, dropped or left in the bowl. Butter at 100% and flour at 100% is a plausible-looking cost that no real kitchen achieves.

Cost the *yielded* quantity: what reaches the customer, divided into what you bought. For anything trimmed or reduced, measure it once in your own kitchen rather than using a book figure.

## Waste is a line item, and it is not the same as yield loss

Yield loss is inherent to the process. Waste is unsold product, failed batches and expiry. Both belong in the cost, and separating them tells you which one to attack — a low-yield method is a recipe problem, high waste is a forecasting problem.

Bakery is unforgiving here: the whole product line has a one-day shelf life, so a 20% end-of-day discard is a fifth of the batch cost with no revenue.

## Price on contribution, not on a fixed multiple

A blanket "three times food cost" prices some items off the market and gives others away. What matters is the cash contribution per item and per hour of oven or bench time.

A low-margin loaf that fills the oven while the high-margin item proves may be the right thing to keep. Decide with the arithmetic in front of you.

## Scaling breaks at bakers' percentages, not at multiplication

Doubling a dough does not double mixing time, proving time or oven load, and hydration behaves differently at volume. Scale by bakers' percentage against total flour weight, then re-test — the first scaled batch is a trial, not production.

Salt, yeast and leavening are where naive scaling fails most visibly.

## Watch out for

- Ingredient prices that moved since the recipe was costed, especially dairy, eggs and flour.
- Packaging, labels and bags left out of the cost entirely.
- Labour costed as an overhead when one item takes four times the bench time of another.
- The same sub-recipe costed differently in two places.
- Menu prices ending in a psychologically chosen number that has drifted below cost.

## Finishing

Every cost uses yielded quantities measured in this kitchen. Waste and yield loss are separated. Prices state contribution per item, not just a multiple.
`,
  },
  {
    name: "food-service-operations",
    category: "Tools & Automation",
    roles: ["Restaurant General Manager", "Guest Experience Coordinator", "Store Manager", "Head Baker"],
    description:
      "Runs a service that holds up when it gets busy. Use when the peak is going wrong, prep and demand are mismatched, or quality varies by shift.",
    body: `
# Food Service Operations

## The constraint moves, and you must know where it is

At any moment one thing limits throughput: a station, an oven, the pass, the till, the dish pit. Adding staff anywhere else changes nothing and makes the space worse.

Watch where the queue forms. That is the constraint, and it moves between dayparts — the morning constraint is rarely the evening one.

## Prep is a forecast, and forecasts are checkable

Prep too little and you sell out of the thing people came for. Prep too much and you discard margin. Both are failures of the same estimate.

Keep the actual against the forecast by day of week. Weather, local events and paydays are real signals; a manager's feel usually is not, and the record settles it either way.

## Consistency comes from the build, not from the recipe

Two cooks reading the same recipe produce different plates. What removes the variance is a specified build: same scoop, same order, same finish, checked at the pass.

Write the spec down with a photograph. A verbal standard drifts by a shift and is unrecoverable by the next one.

## Recovering a bad experience beats preventing complaints

Things go wrong in every service. What decides whether the guest returns is what happened next — acknowledged fast, fixed without argument, by someone empowered to fix it.

Give the shift a standing allowance to resolve a problem on the spot. Escalation for a wrong order costs more in goodwill than the dish.

## Watch out for

- Holding times exceeded because nothing is timestamped.
- The cleaning schedule slipping first when a shift is short — the most expensive corner to cut.
- Allergen handling treated as a labelling task rather than a preparation one.
- Temperature logs completed retrospectively, which makes them worthless as evidence.
- One person on the rota whose absence stops service.

## Finishing

The current constraint is identified and staffed. Prep tracks forecast against actual. Every repeated item has a written, photographed build.
`,
  },

  /* ------------------------------------------------ Media & Communications */
  {
    name: "video-production-workflow",
    category: "Design & Creative",
    roles: ["Video Producer", "Executive Producer", "Podcast Producer"],
    description:
      "Gets a video finished without a re-shoot or a lost file. Use when planning a shoot, organising an edit, or a project has stalled in post.",
    body: `
# Video Production Workflow

## Everything expensive is decided before the camera is on

The re-shoot is the only genuinely unrecoverable cost in video. It is nearly always caused by something knowable in advance: no shot list, unclear approval, an unbooked location, missing consent.

Lock the edit's structure before shooting. Shooting to find the story means covering everything, which is how a one-day shoot becomes three.

## Sound is the half people notice

Audiences forgive soft focus and forgive grade. They stop watching bad audio within seconds. Budget and attention should follow that, which usually means a separate recorder, a lav on anyone speaking, and thirty seconds of room tone in every location.

Record room tone. The edit will need it and you cannot fake it afterwards.

## Name and back up at the card, not in the edit

Files get renamed once, at ingest, to a scheme that survives being seen out of context: date, project, camera, card, take. Two copies before the card is formatted, one of them off-site.

A project lost to a single drive is a project lost entirely, and it happens to people who knew better.

## Review in passes, not all at once

Structure first — is this the right order and length. Then picture. Then sound. Then grade and titles. Mixing the passes produces notes on a colour grade for a scene that gets cut, which wastes the reviewer's attention and the editor's day.

Give each review a named question and a deadline.

## Watch out for

- Music without a licence that covers the actual distribution.
- Appearance releases missing for anyone identifiable, which surfaces at publication.
- Aspect ratio and captions decided after the edit rather than before framing.
- Approval by a group with no named decider.
- No archive of the finished project's source files and edit data.

## Finishing

The edit structure was agreed before the shoot. Audio was recorded separately with room tone. Files are named to a scheme with two copies. Every review pass had one question.
`,
  },
  {
    name: "public-relations-and-media-response",
    category: "Sales & Marketing",
    roles: ["Public Relations Manager", "Communications Director", "Communications Assistant", "Brand Designer"],
    description:
      "Earns coverage and handles the difficult story. Use when pitching a journalist, preparing a statement, or something has gone wrong publicly.",
    body: `
# Public Relations and Media Response

## A pitch is a story for their readers, not news about you

A journalist's question is always the same: why would my audience care today. A funding round, a hire or a milestone answers that only if it evidences something the audience already argues about.

Lead with the claim and the evidence. Include the data, the name, the number. A pitch that requires a follow-up call to become interesting will not get one.

## Speed and accuracy trade against each other, and silence is a position

In a bad story, the first hours set the frame. But a wrong first statement becomes the story itself and forces a correction cycle you will not control.

So publish what you can stand behind: what happened, what you are doing, when you will say more. Say what you do not yet know rather than filling it. "No comment" reads as confirmation to every audience.

## Never speculate on cause while it is being established

The strongest position in a difficult story is a narrow, true statement with a named next update. The weakest is an early theory that later turns out wrong, because it converts one story into two.

## Correct fast and completely

A partial correction extends the story. Correct the record plainly, once, in the same channel, without relitigating. Nobody has ever been damaged by a clean correction as much as by a defended error.

## Watch out for

- Embargoes broken by an internal share, which ends a relationship with that journalist permanently.
- Spokespeople who have not been briefed on the difficult question.
- A holding statement that promises a timeline you cannot meet.
- Internal communication that will obviously leak, drafted as if it will not.
- Legal and communications giving contradictory advice with no one reconciling them.

## Finishing

Every pitch names why this audience cares now, with evidence. Statements contain only what can be stood behind, plus a next-update time. Corrections were made plainly and once.
`,
  },
  {
    name: "editorial-standards",
    category: "Documents & Communication",
    roles: ["Copy Editor", "Communications Assistant", "Senior Content Writer", "Content Writer"],
    description:
      "Makes copy correct, consistent and checkable without flattening the writer's voice. Use when editing for publication, setting a style rule, or a claim needs verifying.",
    body: `
# Editorial Standards

## Separate the four passes, or do none of them well

Substance: is it true and does it hold together. Structure: is it in the right order. Line: does each sentence work. Proof: spelling, punctuation, consistency.

Mixed together, you rewrite sentences that get cut and miss a factual error while fixing a comma. Substance first, always — it is the pass most likely to change everything downstream.

## Every factual claim gets a source or a hedge

A number, a date, a superlative or an attributed quote is either verified or softened. "The largest in Europe" needs a source and a date; without one it becomes "among the largest", or it goes.

This is the difference between editing and proofreading, and it is where an editor earns their place.

## A style guide exists to stop re-deciding

Serial comma, capitalisation of job titles, number formatting, date format, how the company name is written. Decide once, write it down, apply it. The point is not correctness — several answers are defensible — it is that nobody spends attention on it twice.

## Edit toward the writer's voice, not your own

The test for a line edit is whether the sentence says the thing more clearly, not whether it sounds more like you. Where a writer's construction is unusual but works, leave it.

Change of meaning always goes back to the writer as a question, never as a silent fix.

## Watch out for

- Hedging inserted so heavily the piece stops claiming anything.
- Passive constructions hiding who did something, in the exact places it matters.
- Headings and body text drifting apart after a restructure.
- Links unchecked, or pointing somewhere that no longer says what was cited.
- Consistency enforced so hard that a quotation gets silently altered.

## Finishing

Substance was checked before line-level work. Every factual claim is sourced or hedged. Style decisions came from the guide. Meaning changes went back to the writer.
`,
  },

  /* ------------------------------------------------------ Retail & E-commerce */
  {
    name: "ecommerce-merchandising",
    category: "Sales & Marketing",
    roles: ["E-commerce Manager", "Head of E-commerce", "Merchandising Specialist", "Marketplace Specialist", "Store Manager"],
    description:
      "Arranges a catalogue so people find and buy the right things. Use when conversion is flat, a category underperforms, or a range needs planning.",
    body: `
# E-commerce Merchandising

## Diagnose by step, not by the overall number

Conversion is a chain: found, viewed, added, checked out, paid. A single conversion figure hides which link is broken, and the fixes are unrelated — a discovery problem is not a checkout problem and no amount of product photography solves it.

Get the drop-off per step before changing anything.

## Search and filters are the storefront for anyone with intent

A customer who searches converts several times better than one who browses, and a customer who searches and finds nothing usually leaves for good. So zero-result searches are the highest-value report in the business: they are demand you have, expressed in the customer's own words, unmet.

Read them weekly. They tell you what to stock, what to rename and what to redirect.

## A product page answers objections in order

Will it fit me, is it right for my use, what does it really look like, when will it arrive, what if I am wrong. Reviews, dimensions, delivery date and returns policy are not trust decoration — each removes one specific reason not to buy.

Missing delivery dates and missing return terms are the two commonest abandoned-cart causes that have nothing to do with price.

## Range decisions are about cash, not choice

Every SKU consumes working capital, warehouse space and attention. Rank by contribution and rate of sale, then act: the long tail that neither sells nor differentiates is funding nothing.

Deliberate exceptions are fine — a hero item that brings people in, a size that completes a range — but name them as exceptions.

## Watch out for

- Out-of-stock items still indexed and advertised, spending money to disappoint.
- Category pages sorted by "featured" with nobody able to say what that means.
- Discounting used to move stock that a better description would have sold.
- Marketplace listings drifting out of sync with the main catalogue's prices and stock.
- Mobile experience judged on a desktop screen, where most of the traffic is not.

## Finishing

Drop-off is known per funnel step. Zero-result searches are reviewed regularly. Product pages answer fit, use, appearance, delivery and returns. Range decisions state contribution and rate of sale.
`,
  },
  {
    name: "inventory-and-replenishment",
    category: "Data & Analytics",
    roles: ["Merchandising Specialist", "Store Manager", "Logistics Coordinator", "Senior Supply Planner", "Production Planning Assistant", "Retail Assistant"],
    description:
      "Holds enough stock to sell and not so much that it ties up cash. Use when setting reorder points, a line keeps selling out, or stock is aging.",
    body: `
# Inventory and Replenishment

## Two failures, and they are not symmetrical

A stockout loses a sale and sometimes a customer. Excess stock ties up cash and eventually gets discounted. Which is worse depends entirely on the item: for a staple, stockout is far more expensive; for a seasonal or perishable line, excess is.

Say which failure you are optimising against before choosing a service level. A blanket 95% across the whole catalogue is a decision nobody made.

## Reorder point is lead time times demand, plus the safety buffer

The buffer covers *variability*, not the average — and variability in lead time usually hurts more than variability in demand, because it is outside your control and lumpy.

Measure actual supplier lead times rather than quoted ones. The gap is often large and is where most stockouts originate.

## Forecast at the level the decision is made

Forecasting a category then splitting it by last year's mix produces confident nonsense at the SKU level, which is where the purchase order gets written. Forecast where you order.

Keep the forecast error by SKU. A line you consistently under-forecast needs a bigger buffer, not more meetings.

## Aging stock is a decision being avoided

Stock that has not moved in two cycles will not start. The value is highest today and falls from here, so the choice is between acting now at a known discount or later at a worse one.

Age the inventory visibly and set a rule — mark down, bundle, return or write off at a defined point — so the decision happens on schedule rather than when someone notices.

## Watch out for

- Counted stock diverging from system stock, which invalidates every calculation above it.
- Minimum order quantities silently setting your stock level instead of the demand doing it.
- Promotions run without adjusting the replenishment, causing a stockout mid-campaign.
- One supplier for a critical line, with no qualified alternative.
- Safety stock raised after every stockout and never lowered.

## Finishing

Service levels differ by item type with a stated reason. Reorder points use measured lead times. Forecasts exist at ordering level with tracked error. Aging stock has a defined action point.
`,
  },

  /* ------------------------------------------- People, Hiring & Administration */
  {
    name: "structured-hiring",
    category: "Documents & Communication",
    roles: ["Senior Recruiter", "Recruiter", "HR Coordinator", "People Operations Lead"],
    description:
      "Runs a hiring process that predicts performance and can be defended. Use when writing a role, designing an interview, or a shortlist decision is contested.",
    body: `
# Structured Hiring

## Define what the person must be able to do, not who they must be

Years of experience and a degree predict performance weakly. A concrete statement of the work — "can take a vague request from a non-technical owner and ship a working page in a week" — predicts it far better and can actually be assessed.

Write that before sourcing. A role definition arrived at by looking at candidates is a definition shaped by who happened to apply.

## The same questions in the same order, or you have no comparison

Unstructured interviews measure rapport. The interviewer feels informed and the signal is close to noise. Structure — same questions, same scoring guide, notes taken during rather than after — is the single largest improvement available.

Score independently before discussing. A group that talks first converges on whoever spoke first, and that is not a decision.

## A work sample beats a conversation about work

Ask for the actual thing, small: review this code, plan this launch, cost this menu. Timeboxed, paid if it is substantial, and the same task for every candidate.

Unpaid multi-day exercises select for people who can afford them, which is not the trait you are hiring for.

## Rejection is part of the product

Every candidate is a potential customer and a source of referrals. Reply, reply reasonably fast, and be specific enough to be useful without being litigable.

Silence after a final-stage interview is the single most-remembered failure of a hiring process.

## Watch out for

- Criteria added mid-process, which almost always rationalises a preference formed earlier.
- "Culture fit" standing in for similarity to the interviewer.
- Referrals skipping the structure — the same bar or a documented exception.
- Salary bands discovered at offer stage after everyone's time is spent.
- Notes that record impressions rather than what the candidate actually said or did.

## Finishing

The role names assessable capabilities. Every candidate got the same questions and an independent score before discussion. Work samples were timeboxed and identical. Everyone received a reply.
`,
  },
  {
    name: "employee-onboarding",
    category: "Documents & Communication",
    roles: ["HR Coordinator", "Learning & Development Specialist", "Administrative Assistant", "People Operations Lead", "Executive Assistant"],
    description:
      "Gets a new person productive and staying. Use when someone is joining, onboarding feels chaotic, or early attrition is high.",
    body: `
# Employee Onboarding

## Day one is a signal about the whole organisation

An account that does not work, no laptop, nobody expecting them: the new person concludes something accurate about how things are run, and it is hard to undo.

Everything mechanical — access, equipment, payroll, a named first contact — is done before they arrive, not on the morning.

## Give a real task in the first week

Not training, not shadowing: something small that ships. It converts abstract onboarding into orientation with a purpose, and it surfaces the gaps in your setup faster than any checklist.

The first task should be genuinely useful and genuinely small. A trivial task insults; a large one strands.

## Front-load context, not process

What the business actually does, who the customer is, what is currently hard, who decides what. Process documentation can be read when needed; context cannot be looked up and is what makes their judgement usable.

## Thirty, sixty, ninety with real questions

Fixed check-ins with specific questions — what is still unclear, what has taken longer than it should, what surprised you — surface fixable problems while they are still cheap.

The new person is the only one who can see your onboarding clearly, and only for about a month. Write down what they say; it is the input for the next hire.

## Watch out for

- A buddy assigned who was not asked and has no time.
- Access granted broadly on day one because narrowing it later is effort.
- Onboarding that ends at the equipment handover.
- The same question asked by every new joiner and never written down.
- Probation reviews held with no record of what was agreed at the start.

## Finishing

Everything mechanical was ready before arrival. A small real task shipped in week one. Context came before process. Check-ins happened and their answers changed the next onboarding.
`,
  },

  /* ---------------------------------------------- Travel, Tourism & Events */
  {
    name: "event-planning-and-run-of-show",
    category: "Tools & Automation",
    roles: ["Senior Event Planner", "Events Director", "Event Assistant", "Guest Experience Coordinator", "Corporate Travel Manager"],
    description:
      "Delivers an event that runs on time when something goes wrong. Use when planning a run of show, sizing a budget, or an event is close and unresolved.",
    body: `
# Event Planning and Run of Show

## The run of show is the deliverable

Not the plan, not the deck: a minute-by-minute document naming what happens, who does it, and who decides if it slips. On the day, nobody reads anything else.

Include the transitions. Events run late in the gaps between items, not during them.

## Every dependency has an owner and a deadline that is not the event

Catering, AV, venue access, permits, signage, speakers' materials. A dependency whose deadline is "the event" is a dependency that will be discovered on the day.

Work backwards from the door opening, and put the AV test earlier than feels necessary. It is always the thing that fails.

## Contingency is specific, not a percentage

"Ten per cent buffer" is not a plan. What if the keynote does not arrive, the stream drops, it rains, twice the expected number turn up, half do. Each needs a named response and someone empowered to trigger it.

Write the three most likely failures and their responses on the run of show itself.

## Attendance is a forecast, and no-show rates are knowable

Free events no-show heavily; paid ones much less. Catering, seating and staffing all key off that number, and guessing it is how you either waste half the food or run out in twenty minutes.

Use your own past rate where you have one. Say which figure you used and why.

## Watch out for

- Accessibility treated as a late addition rather than a venue-selection criterion.
- Speakers who have not seen the actual stage timing or been told their real slot.
- One person holding every supplier relationship in their own inbox.
- A budget with no line for overtime, damage or last-minute AV.
- Nobody assigned to the door in the first fifteen minutes, which is when arrival peaks.

## Finishing

A minute-by-minute run of show names owners and deciders, including transitions. Every dependency has a pre-event deadline. The three likeliest failures have written responses. Attendance uses a real no-show rate.
`,
  },

  /* -------------------------------------------------- Nonprofit & Community */
  {
    name: "grant-writing-and-reporting",
    category: "Documents & Communication",
    roles: ["Grant Strategy Manager", "Fundraising Manager", "Programs Director", "Nonprofit Executive Director"],
    description:
      "Wins funding you can actually deliver against, and reports honestly. Use when writing an application, choosing which to pursue, or a report is due on a programme that underperformed.",
    body: `
# Grant Writing and Reporting

## Choose which to apply for before writing anything

An application takes real hours and displaces delivery. Score candidates on fit with what you already do, size against effort, restriction terms, and whether the reporting burden is survivable.

A grant that pays for work you would not otherwise do is a strategy change wearing a funding disguise. Sometimes right — but decide it deliberately.

## Answer the question they asked, in their words

Funders read many applications against a rubric. Reusing a generic case for support and hoping it maps costs you the easy marks. Use their terminology, their outcome framing, their section order.

Where you cannot answer well, say so briefly rather than padding. Assessors recognise padding and it costs more than the gap.

## Outcomes are what changed, not what you did

"Ran twelve workshops" is an activity. "Sixty-two participants, of whom forty-one entered work within six months, measured by follow-up survey at 71% response" is an outcome with its own limitation stated.

Name the measurement method and its weaknesses. An outcome with no method is not evidence, and assessors know it.

## Budget honestly, including overheads

Under-costing to look efficient means delivering at a loss and being unable to report success. Include the staff time, the management cost and the reporting effort the grant itself creates.

If a funder disallows overheads, that is a real cost of that money — price it into the decision rather than absorbing it invisibly.

## Report the shortfall before you are asked

A programme that missed its target and says so, with cause and what changed, keeps its funder. One that reframes the miss loses trust permanently, and funders talk to each other.

## Watch out for

- Restricted funds spent on general costs, which is the fastest route to losing a funder.
- Outcomes promised at a scale the staffing cannot reach.
- The same beneficiaries counted in several programmes' numbers.
- Reporting deadlines missed on renewals that were otherwise certain.
- A dependence ratio nobody has calculated — one funder at 60% is a strategic risk.

## Finishing

The application was chosen against explicit criteria. Answers use the funder's framing. Outcomes state measurement method and limitations. The budget includes overheads and reporting effort.
`,
  },

  /* ----------------------------------- Real Estate, Construction & Trades */
  {
    name: "property-and-facilities-management",
    category: "Tools & Automation",
    roles: ["Property Manager", "Field Service Coordinator", "Trade Business Assistant", "Construction Program Director"],
    description:
      "Keeps buildings working and tenants dealt with fairly. Use when triaging maintenance, planning preventive work, or a compliance date is approaching.",
    body: `
# Property and Facilities Management

## Triage by consequence, not by who complained loudest

Safety and habitability first: no heat, no water, electrical fault, anything that makes a home unsafe or legally uninhabitable. Then things that get worse if left — a leak damages structure at a rate a dripping tap does not. Then everything else.

Publish the categories and the target response for each. Most tenant frustration is about not knowing when, not about waiting.

## Preventive work is cheaper, and the arithmetic is not close

A serviced boiler and a cleared gutter cost a fraction of the failure they prevent, and the failure arrives with emergency call-out rates and consequential damage.

Keep a calendar per asset with its service interval, and treat a missed service as an incident. Deferred maintenance is borrowing at a rate nobody records.

## Compliance dates are hard dates

Gas, electrical, fire safety, legionella, asbestos, insurance — each with its own interval and its own evidence requirement. Late is not a paperwork problem; it can void insurance and, if something happens, it is the first thing examined.

Track them with a reminder well before expiry, because contractors are not always available on your timeline.

## Document at the time, in the tenant's presence where possible

Photographs, dates, what was said, what was agreed. Deposit disputes and access disagreements are decided on records, and a record written weeks later carries little weight.

## Watch out for

- Access notice periods shortened for convenience, which is often unlawful.
- One contractor with no alternative for an urgent trade.
- Deposit deductions with no condition evidence from move-in.
- Recurring faults treated as separate jobs, hiding a single underlying cause.
- Communal areas with no named responsibility.

## Finishing

Requests are categorised by consequence with published response targets. Every asset has a service interval and a calendar. Compliance dates are tracked with early reminders. Records were made at the time.
`,
  },

  /* --------------------------------------- Healthcare & Wellness Operations */
  {
    name: "clinic-operations",
    category: "Healthcare & Science",
    roles: ["Clinic Practice Manager", "Patient Experience Manager", "Care Administration Coordinator", "Fitness Business Manager"],
    description:
      "Runs a practice so clinical time is used well and patients are treated properly. Use when the schedule is failing, no-shows are high, or an administrative process is causing harm.",
    body: `
# Clinic Operations

## Clinical time is the constraint, and everything else exists to protect it

Every administrative decision either adds to or removes from time with patients. Measure how much of a clinician's day is spent on things someone else could do — and it is usually far more than anyone assumes.

That is the frame for every process question here.

## The schedule fails at the joins

Overrunning appointments cascade, and the last patient of the session absorbs the whole day's slippage. Fixed slot lengths for genuinely variable consultations guarantee this.

Match slot length to appointment type, keep deliberate catch-up gaps, and measure actual duration by type rather than defending the nominal figure.

## No-shows are a system output

Charging for them mostly moves the cost to the people least able to bear it. What actually reduces them: reminders at a useful interval, easy rescheduling, and knowing which appointment types and times fail most.

Look for the pattern before the penalty. A slot nobody can reach by public transport at 9am is not a patient-motivation problem.

## Handle data as if it will be audited, because it may be

Access on a need-to-know basis, audited. Consent recorded for what it actually covers. Retention and deletion on a schedule. Never patient-identifiable information in an unsecured channel, however convenient.

A practice's data handling is the part patients cannot check and most rely on.

## Watch out for

- Results or referrals with no closed loop, so nobody notices one was never actioned.
- Reception carrying clinical triage informally, without training or protocol.
- Recall lists maintained by hand and quietly falling behind.
- Interpreting or accessibility needs recorded but not surfaced at booking.
- Complaints resolved individually with no pattern review.

## Finishing

Administrative load on clinical time is measured. Slot lengths match measured durations by type. No-show patterns were examined before penalties. Data access is need-to-know and audited. Results and referrals have closed loops.
`,
  },

  /* --------------------------------------- Legal, Compliance & Risk */
  {
    name: "contract-review",
    category: "Security",
    roles: ["Contract Manager", "General Counsel", "Paralegal Assistant", "Risk Manager", "Procurement Specialist"],
    description:
      "Reads a contract for what could actually go wrong. Use when reviewing terms, negotiating a clause, or deciding whether a risk is worth accepting.",
    body: `
# Contract Review

## Read for failure, not for meaning

Anyone can read what a contract says when things go well. The value is in what happens when they do not: who bears the loss, who can walk away, what it costs to leave, and who decides.

Go to liability, indemnity, termination, and dispute resolution first. Those four decide the actual exposure.

## Unlimited liability is the clause to find first

Caps, exclusions and carve-outs from the cap are where a commercially small deal becomes an unbounded one. Read the carve-outs especially: a cap with broad exceptions is not a cap.

Check the cap against the contract value. Unlimited liability on a low-value agreement is rarely a deal anyone would sign deliberately.

## Termination is about cost, not about rights

Everyone has a right to terminate somewhere. What matters is notice period, what survives, whether fees continue, whether you get your data back and in what format, and how long transition takes.

Auto-renewal with a short cancellation window is the most commonly overlooked trap and the easiest to fix.

## Distinguish what you would change from what you must

A review producing forty comments gets ignored or delays the deal. Rank: must-change to sign, should-change if possible, noted-and-accepted.

Naming what you are accepting is itself the deliverable — it means the risk was chosen rather than missed.

## Watch out for

- Governing law and jurisdiction making enforcement impractical whatever the terms say.
- Indemnities that are not mutual where the risk is.
- IP ownership of things created under the contract left ambiguous.
- Data-processing terms absent where personal data is obviously involved.
- Incorporated documents by reference — the linked policy the other side can change unilaterally.
- A signature block naming an entity that is not the one with the assets.

## Finishing

Liability, indemnity, termination and disputes were read first. Caps were checked against value including carve-outs. Comments are ranked must / should / accepted. Accepted risks are named explicitly.
`,
  },

  /* --------------------------------------- Supply Chain & Manufacturing */
  {
    name: "supplier-management",
    category: "Tools & Automation",
    roles: ["Procurement Specialist", "Supply Chain Director", "Senior Supply Planner", "Quality Systems Specialist", "Sustainable Sourcing Specialist"],
    description:
      "Chooses and manages suppliers on total cost and risk rather than unit price. Use when selecting a supplier, a delivery is failing, or a single source is a concern.",
    body: `
# Supplier Management

## Unit price is the smallest part of total cost

Freight, duty, payment terms, minimum order quantity, defect rate, lead-time variability, the cost of your own time managing them. A cheaper unit price with a 4% defect rate and erratic lead times is more expensive, often by a lot.

Compare landed cost per usable unit. That is the only comparison that means anything.

## Single-sourcing is a decision that must be made explicitly

Sometimes it is right: better price, better relationship, genuine uniqueness. But it is a bet, and it should be a named one with a qualified alternative identified even if unused.

The time to find a second supplier is not while the first has stopped delivering.

## Measure performance or do not claim to manage it

On-time-in-full, defect rate, responsiveness, quoted versus actual lead time. Reviewed on a schedule, shared with the supplier.

A supplier who has never seen their own numbers cannot improve, and a relationship without measurement runs on how recent the last complaint was.

## Escalate on a path, not on frustration

Operational contact, then their manager, then commercial, then the contract. Each with a stated timeframe. Jumping to the contract on a first miss burns the relationship you will still need next month; never escalating means nothing changes.

## Watch out for

- Payment terms conceded for a small discount, and the working-capital effect not calculated.
- Quality agreed verbally and not specified, so "defect" is arguable.
- A supplier who is a reseller you cannot see behind, with hidden concentration risk.
- Concentration by geography or logistics route rather than by supplier name.
- Long relationships never re-tendered, where the price drifted well off market.

## Finishing

Comparisons use landed cost per usable unit. Single-sourcing is deliberate with an identified alternative. Performance is measured, scheduled and shared. Escalation follows a path with timeframes.
`,
  },

  /* ------------------------------------------ Education & Knowledge */
  {
    name: "instructional-design",
    category: "Research & Knowledge",
    roles: ["Learning & Development Specialist", "Director of Learning", "Teaching Assistant", "Knowledge Manager", "Curriculum Developer"],
    description:
      "Designs learning that changes what someone can do. Use when building a course, a session is not landing, or training is being requested for a problem it may not fix.",
    body: `
# Instructional Design

## Ask whether training is the right intervention

Much requested training addresses a problem it cannot fix: unclear process, missing tool, wrong incentive, or a task done twice a year that should be a checklist instead.

Training changes capability. If the person already knows and still cannot do it, the obstacle is elsewhere and a course will waste everyone's time while appearing to respond.

## Start from what they must be able to do

Write the objective as an observable action: "can reconcile a bank statement and explain each difference", not "understands reconciliation". If you cannot say how you would see it, you cannot design toward it or assess it.

Everything in the material either serves an objective or comes out.

## Practice with feedback is the mechanism; everything else is preparation

People learn by attempting and finding out how they did. Content sets that up. A session that is all explanation and no attempt feels efficient and transfers little.

Aim for most of the time spent doing, with feedback close to the attempt. Delayed feedback teaches much less.

## Design for forgetting

Learning decays fast without retrieval. Spacing, a small amount of revisiting, and a job aid for the parts nobody should memorise beat a longer single session at any total time budget.

Not everything should be learned. Some things should be looked up, and deciding which is design work.

## Watch out for

- Assessment testing recall of the material rather than the objective.
- A course covering everything known rather than what is needed.
- Learner effort spent on navigation and formatting instead of the subject.
- Accessibility retrofitted after production.
- Success measured by completion and satisfaction, which correlate weakly with capability.

## Finishing

Training was confirmed as the right intervention. Objectives are observable actions. Most time is practice with close feedback. Spacing and job aids handle retention. Assessment tests the objective.
`,
  },

  /* ------------------------------------------- Leadership & Strategy */
  {
    name: "operating-cadence",
    category: "Tools & Automation",
    roles: ["Chief of Staff", "General Manager", "Strategy Director", "Executive Assistant", "Retail Operations Manager"],
    description:
      "Sets the rhythm of meetings, decisions and reporting that keeps a business moving. Use when meetings are consuming the week, decisions stall, or nobody knows the current priorities.",
    body: `
# Operating Cadence

## A cadence exists to make decisions, not to share information

Any meeting whose output is that everyone now knows something should have been a document. The meetings worth holding are the ones where a decision gets made or a disagreement gets resolved.

Every recurring meeting needs a stated decision it exists to make. Those that cannot name one get cancelled, and almost nothing happens.

## Separate the horizons, or they collide

Weekly is execution: what is blocked, what changed, who needs what. Monthly is performance against plan. Quarterly is direction. Mixing them means either strategy displaced by an urgent operational issue, or an operational blocker waiting a quarter.

Different cadence, different attendees, different preparation.

## Written before, discussed during

A document circulated in advance, read before the meeting, turns an hour of presentation into an hour of argument about the real question. Presenting live guarantees the reading happens at the speed of the slowest reader and nobody challenges anything.

Silent reading at the start is better than hoping. It costs ten minutes and it works.

## A decision without a name and a date is not a decision

Record what was decided, who owns it, when it lands, and — most valuably — what was decided *against* and why. Six weeks later the same option returns and the reasoning is gone.

Revisit deliberately when something changes, not because someone forgot.

## Watch out for

- A standing agenda nobody has questioned in a year.
- Attendees who never speak, which is either a signal about the meeting or about them.
- Metrics reported because they are available rather than because they drive a decision.
- Actions carried forward repeatedly, which usually means unowned or too large.
- Escalation happening in side channels because the cadence is too slow.

## Finishing

Every recurring meeting names the decision it exists to make. Horizons are separated by cadence and attendees. Material is written and read before discussion. Decisions record owner, date and the rejected alternative.
`,
  },

  /* ---------------------------------- Personal Services & Local Business */
  {
    name: "local-reputation-management",
    category: "Sales & Marketing",
    roles: ["Reputation & Reviews Specialist", "Salon & Spa Manager", "Local Business Assistant", "Local Business Growth Manager", "Multi-location Services Director"],
    description:
      "Earns and handles reviews for a business people find locally. Use when ratings are slipping, a bad review needs answering, or local search visibility is poor.",
    body: `
# Local Reputation Management

## Reviews are the storefront for a local business

For anything chosen locally, the rating and the recent reviews are most of the decision, ahead of the website. Volume and recency matter as much as the average — a 4.9 from eleven reviews two years ago reads worse than a 4.5 from two hundred, ongoing.

So the goal is a steady flow, not a high score at one moment.

## Ask everyone, at the right moment, and never buy any

The moment is just after the thing went well, while the person is still present or immediately after. Asked then, plenty of people will. Asked a week later by email, very few.

Never incentivise or fabricate. Platforms detect it, penalties are severe, and a business with obviously bought reviews is worse off than one with none.

## Answer the bad ones for the next reader

The complainant may not come back. The value is in what the next hundred readers see: acknowledged specifically, fixed where fixable, without defensiveness or a legal tone.

One calm, specific reply under a bad review does more for conversion than several good reviews. Arguing does the opposite, permanently.

## Local search is mostly completeness and consistency

Accurate hours including holidays, correct category, photographs that are actually of the place, the same name and address everywhere, and the service list filled in. Unglamorous and it is most of the ranking.

Inconsistent details across directories actively suppress visibility.

## Watch out for

- Review responses written in a legal register, which reads as guilt to every reader.
- Holiday hours never updated, generating the most annoyed reviews of the year.
- One location's reviews dragging a multi-site average with nobody looking per site.
- Photographs that flatter beyond what a visitor will find, which produces disappointment reviews.
- A recurring complaint answered individually many times and never fixed.

## Finishing

Reviews arrive steadily and are asked for at the moment of success. Nothing was incentivised. Negative reviews have calm, specific public replies. Listings are complete and consistent everywhere.
`,
  },

  /* ------------------------------------------------------- Research, Data & AI */
  {
    name: "research-synthesis",
    category: "Research & Knowledge",
    roles: ["Research Director", "Research Assistant", "Senior Research Analyst", "Market Researcher"],
    description:
      "Turns many sources into a defensible answer, and says how confident it is. Use when reviewing literature, comparing conflicting sources, or a question needs an evidence-based answer.",
    body: `
# Research Synthesis

## The question comes first, in a form that can be answered

"What do we know about pricing" produces a reading list. "Would a 10% price rise on our top three lines lose more revenue than it gains, over one quarter" produces a decision.

Write the question so that a possible answer would change what somebody does. If no answer would change anything, the research is not worth doing yet.

## Weight sources, do not merely count them

Ten blog posts citing one study is one study. A primary source beats a summary of it, a large sample beats a small one, a pre-registered result beats a retrospective one, and a source with an interest in the conclusion needs corroboration.

Note the sample, the method and the date on anything load-bearing. A robust 2015 finding about consumer behaviour may simply no longer hold.

## Conflicting evidence is a finding, not a problem to resolve

When good sources disagree, say so and say why: different populations, different definitions, different periods. Averaging them produces a number that describes nothing.

The honest output is often "the evidence supports X in these conditions and Y in those", which is more useful than false certainty.

## Separate what the evidence says from what you conclude

Two sections, always. The evidence is checkable; the recommendation is judgement built on it plus context the sources do not have. Merging them makes the recommendation look like a finding and stops anyone challenging it.

## Watch out for

- Searching until you find agreement, then stopping.
- A citation that does not actually say what it is cited for — check the passage, not the title.
- Absence of evidence reported as evidence of absence.
- Percentages without a base, and changes without a starting point.
- A single striking anecdote outweighing a duller dataset.

## Finishing

The question is answerable and decision-relevant. Sources are weighted with sample, method and date. Conflicts are stated with their reasons. Evidence and recommendation are in separate sections.
`,
  },

  /* ---------------------------------------------------------- Design & Creative */
  {
    name: "creative-direction",
    category: "Design & Creative",
    roles: ["Creative Director", "Brand Designer", "Lead Product Designer"],
    description:
      "Sets and holds a creative direction across work made by several people. Use when output is inconsistent, a brief is vague, or feedback rounds are not converging.",
    body: `
# Creative Direction

## A direction is a set of constraints, not a mood board

"Modern and friendly" constrains nothing and every reviewer reads it differently. A usable direction says what is in and — more importantly — what is out: no stock photography, one accent colour, sentence case throughout, no drop shadows.

Constraints are what let several people produce work that looks like one thing.

## Brief for the decision the work must survive

Who sees this, where, in what state of mind, and what must they do next. A billboard glanced at from a car and a landing page read at a desk are different problems, and a brief that omits this gets solved for the wrong one.

State the one thing that must land if everything else is missed.

## Critique the work against the brief, not against taste

Useful feedback names the brief requirement it fails: "the offer is the third thing you read and it needs to be first". Unhelpful feedback names a preference: "I don't love the blue".

Where the note *is* taste, say so honestly — "this is preference, treat it as optional" — and let the maker decide. Unlabelled preference is what turns three rounds into nine.

## Converge deliberately

Round one explores; round two narrows to a direction; round three refines. Reopening the direction at round three is the single largest cause of creative overrun, and it is nearly always caused by someone joining late.

Name who approves before round one and hold to it.

## Watch out for

- Feedback aggregated from a committee with no reconciliation, producing contradictory notes.
- Accessibility and contrast treated as a compliance pass rather than a design constraint.
- Work reviewed at the wrong size or on the wrong medium.
- The strongest idea killed because it was unfamiliar rather than wrong.
- A direction that lives only in one person's head and cannot be applied without them.

## Finishing

The direction states what is out as well as in. Briefs name the audience, context and the one thing that must land. Notes cite the brief or are labelled preference. Approval was named before round one.
`,
  },

  /* ------------------------------------------------------- Marketing & Content */
  {
    name: "social-media-management",
    category: "Sales & Marketing",
    roles: ["Social Media Manager", "Community Engagement Coordinator", "Growth Marketing Lead", "Content Writer"],
    description:
      "Runs social accounts that build an audience rather than fill a calendar. Use when engagement is falling, planning a content mix, or something is going wrong publicly.",
    body: `
# Social Media Management

## Posting frequency is not the strategy

A full calendar of forgettable posts trains an audience to scroll past you. One thing a week that is genuinely worth someone's attention outperforms daily filler on every metric that matters.

Decide what you have to say that nobody else can. If the answer is nothing this week, post nothing.

## Each platform is a different medium

The same message needs different form, length and register per platform, and cross-posting identical content signals that none of them matter to you. Native format wins: vertical video where that is the norm, a real thread where that is the norm.

Pick the two platforms where your audience actually is and do them properly, rather than six badly.

## Measure the metric that connects to the business

Impressions and follower count move for reasons unrelated to outcomes. Saves, shares, profile visits and click-through connect to intent; conversions connect to revenue.

Report the connected ones. A post with 50,000 impressions and no clicks was entertainment you paid for.

## Reply, and reply as a person

The comments are the product on social. An account that broadcasts and never answers is a billboard with extra steps. Fast, specific, human replies build more than the posts do.

Never argue in public. Move a genuine dispute to a private channel in one reply and resolve it there.

## Watch out for

- Scheduled posts running through a crisis or a national event — always have a pause procedure.
- Trend participation with no connection to what you do, which reads as desperate.
- Engagement bait that briefly works and trains the algorithm to show you to the wrong people.
- User content reposted without permission or credit.
- One person holding every account password with no recovery path.

## Finishing

Frequency follows having something to say. Content is native per platform, on the two that matter. Reporting uses intent and revenue metrics. Replies happen fast and as a person. A pause procedure exists.
`,
  },

  /* ----------------------------------------------- Sales & Customer Success */
  {
    name: "customer-retention",
    category: "Sales & Marketing",
    roles: ["Customer Success Manager", "Customer Support Specialist", "Sales Manager"],
    description:
      "Keeps customers by noticing trouble before they leave. Use when churn is rising, planning a renewal, or an account has gone quiet.",
    body: `
# Customer Retention

## Churn is decided long before the cancellation

By the time someone asks to leave, the decision is usually weeks old and the conversation is a formality. Saving accounts at that point is expensive and mostly fails.

So the work is early: noticing the account that stopped using the thing it bought, whose champion left, whose usage halved. Those are the intervention points.

## Usage is the signal; satisfaction surveys are not

A customer can report satisfaction and not renew, and can complain constantly while renewing every year. What predicts renewal is whether they are getting the value they bought — visible in usage, in which features, by how many people.

Define the two or three behaviours that mean "getting value" for your product, and watch those.

## The renewal conversation is about outcomes achieved

Not features shipped and not relationship. What did they set out to do, what happened, and what is next. That framing also surfaces honestly when the answer is "nothing much", which is information you need before the renewal date rather than at it.

## Ask why, and believe the answer

Departing customers will usually tell you plainly if you ask without arguing. Record the reason in their words, not the category you would have chosen.

Aggregate them. Three accounts leaving for the same fixable reason is a roadmap item; treated individually it stays invisible.

## Watch out for

- A single champion, whose departure ends the account with no warning.
- Discounting a renewal without addressing why they were leaving — it buys one cycle.
- Support tickets resolved individually with no pattern review.
- Onboarding declared complete when setup finished rather than when value started.
- Health scores computed from fields nobody maintains.

## Finishing

Value behaviours are defined and watched. Intervention happens on usage signals, not on notice. Renewals discuss outcomes achieved. Departure reasons are recorded verbatim and aggregated.
`,
  },

  /* --------------------------------------------- Finance & Business Operations */
  {
    name: "cash-flow-management",
    category: "Data & Analytics",
    roles: ["Fractional CFO", "Finance Director", "Bookkeeping Assistant", "Management Accountant", "General Manager"],
    description:
      "Keeps a business solvent while it grows. Use when cash is tight, planning a runway, or profit and bank balance disagree.",
    body: `
# Cash Flow Management

## Profitable businesses run out of money

Profit is an accounting result over a period; cash is what is in the bank on a Tuesday. A growing business consumes cash — stock and wages go out before customers pay — so the faster it grows, the worse the gap.

Anyone reading only the profit line will be surprised, and the surprise arrives as a missed payroll.

## Forecast weekly, thirteen weeks out, and roll it

Monthly is too coarse to see a mid-month trough that breaks you. Thirteen weeks is far enough to act — chase, delay, borrow — and near enough to be worth trusting.

Roll it every week against actuals. The variance teaches you where your assumptions are wrong, which is the real output.

## The cash conversion cycle is the lever

How long stock sits, how long customers take to pay, how long you take to pay. Improving any of the three releases cash permanently without a sale.

Debtor days is usually the quickest win and is mostly an administrative problem: invoice on the day, state terms, chase on a schedule rather than when it becomes urgent.

## Know the floor and what happens near it

Name the minimum balance below which you cannot operate, and what you will do at that level: which payments delay, what facility draws, what gets cut. Decided in advance and written down.

Deciding under pressure produces the expensive choices — the invoice-discounting deal signed in a week.

## Watch out for

- Tax and payroll treated as flexible timing. They are not, and the penalties compound.
- A single large customer whose late payment is an existential event.
- Growth funded by supplier credit that has no headroom left.
- Seasonality forgotten because last year's trough is out of memory.
- A forecast built once and never compared to what happened.

## Finishing

A rolling thirteen-week weekly forecast exists and is compared to actuals. The conversion cycle is measured with a named target. The minimum balance and the actions at it are written down.
`,
  },

  /* -------------------------------------------- Agriculture & Sustainability */
  {
    name: "sustainability-reporting",
    category: "Research & Knowledge",
    roles: ["Sustainability Director", "Sustainable Sourcing Specialist", "Agribusiness Strategy Manager", "ESG Reporting Analyst"],
    description:
      "Measures and reports environmental impact without overstating it. Use when preparing a disclosure, setting a target, or a claim needs to survive scrutiny.",
    body: `
# Sustainability Reporting

## Measure before committing to anything

A target set without a baseline is a press release. You cannot report progress against a number you never established, and retrofitting a baseline later invites exactly the scepticism the report was meant to avoid.

Establish the boundary — which entities, which sites, which period — and hold it constant, or every year-on-year comparison is meaningless.

## Know which scope a number belongs to

Direct emissions, purchased energy, and everything in the value chain are different quantities with different data quality. The third is usually the largest and the least certain, which is precisely why it gets omitted.

Report it with its uncertainty rather than leaving it out. An incomplete figure honestly labelled is far more credible than a tidy one that excludes most of the impact.

## Estimated is not the same as measured, and both are legitimate

Metered consumption is measured. A spend-based emissions factor is an estimate with a wide error. Both belong in a report; conflating them does not.

Label the method per figure. A reader who cannot tell which is which will discount all of it.

## Never claim neutrality you cannot evidence

"Carbon neutral", "sustainable", "eco-friendly" attract regulatory attention and are the claims most often challenged. Offsets have quality and permanence questions that a certificate does not settle.

Say what you did: reduced this by that much, measured this way, offset the remainder with this instrument. Specific and dull survives; broad and confident does not.

## Watch out for

- Boundary changed between years, making an improvement out of a divestment.
- Intensity metrics used to show progress while absolute emissions rose.
- Supplier data accepted unverified where it dominates the total.
- A target with no interim milestones, so nobody can tell if it is on track.
- Selective reporting of the categories that improved.

## Finishing

A baseline and a constant boundary exist. Every scope is reported, including the incomplete one with its uncertainty. Each figure is labelled measured or estimated. Claims state what was actually done.
`,
  },
];
